"""Fixtures for the commit-message rules.

The negatives matter more than the positives here. A gate that blocks legitimate commit
messages gets disabled, and a repository that uses coding agents talks about the vendors
constantly — in provider names, model ids, branch names and prose. Every negative below is
the shape of a real line from such a repository.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from stayfixed import gitenv
from stayfixed.config.loader import CONFIG_FILE, load
from stayfixed.errors import Refusal
from stayfixed.guards.commit import (
    ATTRIBUTION_LABELS,
    LOG_TIMEOUT_SECONDS,
    Offence,
    check_range,
    commits_in,
    offending_lines,
    strip_message,
)
from tests.gitfixture import git, launched_by_the_hook_wrapper

# Per test, not module-wide: most of this file is pure functions, and a module-level skip
# would void the POSITIVES, the NEGATIVES and the one test the mutation entry names — which
# the oracle then reports as "0 test(s) ran", an environment fact dressed as a defect.
needs_git = pytest.mark.skipif(shutil.which("git") is None, reason="git is not installed")

# The block the harness this module exists to defuse actually appends: a footer, a blank line,
# and a trailer — two paragraphs, not one. Shared by the corpus and the strip test below.
CANONICAL_BLOCK = (
    "fix: something real\n"
    "\n"
    "A body paragraph that must survive.\n"
    "\n"
    "\U0001f916 Generated with [Claude Code](https://claude.com/claude-code)\n"
    "\n"
    "Co-Authored-By: Claude <noreply@anthropic.com>\n"
)

POSITIVES = [
    "Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>",
    "Co-authored-by: Claude <noreply@anthropic.com>",
    "co-authored-by: claude opus 5 <noreply@anthropic.com>",
    "Co-Authored-By: Codex <codex@openai.com>",
    "Co-Authored-By: Cursor Agent <agent@cursor.sh>",
    "Coauthored-by: GitHub Copilot <copilot@github.com>",
    "\U0001f916 Generated with [Claude Code](https://claude.com/claude-code)",
    "Generated with Codex",
    "  Generated with [Cursor]",
    "AI-generated",
    "AI generated by Gemini",
    "Signed-off-by: someone <noreply@anthropic.com>",
    "Generated by Claude Code",
    "Co-Authored-By: Windsurf <noreply@codeium.com>",
    "Reviewed-by: GitHub Copilot <copilot@github.com>",
    "Signed-off-by: bot <noreply@mistral.ai>",
    "Tested-by: Cursor Agent <agent@cursor.sh>",
    # A vendor's subdomain: the domain is tried after each label, not only after the `@`.
    "Co-Authored-By: A Bot <bot@eu.api.anthropic.com>",
    # A BARE ADDRESS, angle brackets left off. The value then has no display name to split at,
    # so `address` was the empty string and the domain rule could never fire -- while the very
    # same address in brackets was caught. The third way in past the trailer's value rule, and
    # measured on the shipped module before it was closed.
    "Co-Authored-By: noreply@anthropic.com",
    "Signed-off-by: bot@mistral.ai.",
    # A trailing blank, and a trailing line of nothing but spaces that no editor renders. Both
    # used to empty the final paragraph and make `offending_lines` return `[]` for anything —
    # a one-space bypass of the gate whose whole point is that it cannot be bypassed. They live
    # in the corpus rather than in a test of their own so they stay measured against every
    # later pattern change.
    "fix: thing\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n\n",
    "fix: thing\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n   \n",
    # The canonical harness block, which is *two* paragraphs. It is in the corpus rather than
    # only in the strip test below because the one-paragraph rule flagged it — one of its two
    # lines — so "did it flag anything" was true all along; what was false is the pair of
    # answers the strip test pins.
    CANONICAL_BLOCK,
]

# Vendor words in the places a repository legitimately puts them: subjects, provider names,
# model ids, paths, branch names, human co-authors, and GitHub's own noreply address. The
# last nine are the review corpus the source's patterns flagged: body prose that happens to
# start with the marker words, and people whose names are vendor words.
NEGATIVES = [
    "feat(llm): gate the openai backup to non-local runs",
    "The default provider is the subscription-backed `claude_cli` with low effort.",
    "Model ids: 'claude-opus-5', 'gemini-2.5-pro'.",
    "docs: record that a claude_cli decision can return an empty turn",
    "Co-authored-by: A Person <person@example.com>",
    "refactor: move the codex app-server provider behind the runtime facade",
    "See docs/handbook/codex-provider.md for the local setup.",
    "This branch was cut from the codex inbound-remediation line.",
    "The generated eval matrix is written with the gate CLI, not by hand.",
    "test: assert the anthropic client retries on 529",
    "chore: bump the openai dependency for the embeddings client",
    "Co-authored-by: Someone <someone@users.noreply.github.com>",
    "Signed-off-by: Human <human@example.com>",
    "AI-generated summaries are now cached for 24 h.",
    "ai-generated captions are behind the new feature flag.",
    "AI generated alt text is now opt-in.",
    "generated by a vendor's codegen, checked in on purpose",
    "Co-authored-by: Claude Lemaire <claude.lemaire@example.fr>",
    "Helped-by: Devin Clark <devin@example.com>",
    "Reported-by: Gemini Rossi <g.rossi@example.it>",
    "Tested-by: QA on the cursor-position branch",
    "Acked-by: the partnership team at a vendor",
    "Co-authored-by: Claude <claude@example.org>",
    # A trailer value that does not END at its address is a sentence, not a trailer. These
    # were flagged until the value-ends-at-the-address rule: everything past the `>` fell into
    # the discarded "address" half, so each read as a bare `Copilot`/`Claude Code`/`Devin`
    # trailer -- and under the paragraph walk, one of them standing alone above the harness
    # block was STRIPPED with it. The last is the same hole reached through the domain rule
    # rather than the name rule, so removing either rule's half leaves it measured.
    "Reviewed-by: Copilot <x@y.z> said nothing useful.",
    "Reviewed-by: Claude Code <x@y.z> was consulted and disagreed.",
    "Helped-by: Devin <d@example.com> only on the parser, not the lexer.",
    "Reviewed-by: someone <noreply@anthropic.com> and then a sentence.",
    # Punctuation and THEN a word: the pair to the `PUNCTUATED` corpus below. A rule that
    # looked only at the first character after `>` would read this as a trailer.
    "Co-Authored-By: Claude <noreply@anthropic.com>. See below",
    # The footer rule's own version of the same defect, found a round later on the other rule:
    # `_FOOTER` was anchored at the start only, so ANY line beginning with the words was a
    # footer whatever followed. Measured on the shipped module, this sentence was
    # `[(3, 'generated-with footer')]` inside a real message and `commit strip` deleted it --
    # the failure direction the module docstring calls the worse one, because the range check
    # still catches a trailer the hook left behind and nothing puts a deleted sentence back.
    "Generated with Claude Code and then reviewed by a human.",
    "Generated with Claude Code, reviewed by a human",
    "Generated by Codex and then rewritten by hand",
    # The bound on the bare-address rule above: a value that is one token IS an address, and a
    # value carrying a space is a display name or a sentence. Without the bound, a `-by:` line
    # that merely mentions a vendor address anywhere in its prose becomes a trailer.
    "Reviewed-by: write to bob@anthropic.com about it",
    "Helped-by: the person behind support@openai.com, by mail",
]

# The other side of the footer's bounded tail, and the reason it is not merely "one word after
# the vendor ends it": a real footer carries the product's remaining name, a version, a markdown
# link target, a bracket and trailing punctuation. Each of these is a footer and stays one.
FOOTERS = [
    "\U0001f916 Generated with [Claude Code](https://claude.com/claude-code)",
    "Generated with Codex",
    "  Generated with [Cursor]",
    "Generated by Claude Code",
    "Generated with Claude Opus 5",
    "Generated with Codex.",
    "Generated with Cursor v1.2",
    # A version a capital or a digit leads, read whole: read as a name word, it ends at the `-`.
    "Generated with Claude Code 2.1-beta",
    "Generated with Claude Code (https://claude.com/claude-code)",
    "\U0001f916 Generated with [Claude Code](https://claude.com/claude-code) \U0001f916",
]

# The other side of that rule. Both of these are REAL attributions, and each was lost by one
# of the two tempting spellings of "the value ends at its address" -- measured, not predicted.
# They are the corpus that says the rule must test for a WORD after the LAST `>`, and nothing
# simpler. A gate the canonical trailer plus one typed full stop walks through is not a gate.
UNTERMINATED = [
    # "the value must END at `>`" loses these: no `>` in the value at all.
    "Co-Authored-By: Claude <noreply@anthropic.com",
    "Signed-off-by: bot <bot@mistral.ai",
]
PUNCTUATED = [
    # "anything after `>` is prose" loses all of these -- ordinary trailing punctuation on the
    # canonical trailer, on the domain rule and on the product-name rule alike.
    "Co-Authored-By: Claude <noreply@anthropic.com>.",
    "Co-Authored-By: Claude <noreply@anthropic.com>,",
    "Signed-off-by: Bob <bob@mistral.ai>.",
    "Reviewed-by: GitHub Copilot <copilot@github.com>.",
    "Reviewed-by: GitHub Copilot <copilot@github.com>;",
    "Reviewed-by: GitHub Copilot <copilot@github.com>)",
    "Co-Authored-By: Claude <noreply@anthropic.com>.),",
    # Not ASCII punctuation, and `\w` rather than `[A-Za-z]` is what keeps these on this side.
    "Co-Authored-By: Claude <noreply@anthropic.com>—",
    "Co-Authored-By: Claude <noreply@anthropic.com>…",
    # A doubled bracket, and a display name carrying brackets of its own: the second is why
    # the tail is taken after the LAST `>` and not the first, where the real address below
    # would be read as prose and the trailer missed.
    "Co-Authored-By: Claude <noreply@anthropic.com>>",
    "Co-authored-by: Claude <bot> <noreply@anthropic.com>",
    "Co-authored-by: A > B <noreply@anthropic.com>",
]

# The documented cost of the domain rule: a person whose employer is a vendor is
# indistinguishable from the vendor's bot by address alone. Pinned so the cost is chosen, not
# rediscovered; dropping the domain rule to fix it reddens `POSITIVES` instead.
KNOWN_COST = [
    "Reviewed-by: Alice <alice@openai.com>",
    "Signed-off-by: Bob Smith <bob@mistral.ai>",
]


@pytest.mark.parametrize("line", POSITIVES)
def test_positive_samples_are_flagged(line: str) -> None:
    assert offending_lines(line), f"expected a violation for: {line!r}"


@pytest.mark.parametrize("line", NEGATIVES)
def test_negative_samples_are_untouched(line: str) -> None:
    assert not offending_lines(line), f"false positive on legitimate text: {line!r}"


@pytest.mark.parametrize("line", KNOWN_COST)
def test_a_human_at_a_vendor_domain_is_the_documented_cost(line: str) -> None:
    assert offending_lines(line), f"the domain rule no longer flags: {line!r}"


@pytest.mark.parametrize("line", UNTERMINATED)
def test_a_trailer_whose_closing_bracket_is_missing_is_still_caught(line: str) -> None:
    # One of the two costs the trailer-value rule was spelled to avoid. Read as "the value
    # must end at `>`", this shape cannot satisfy it -- and a harness trailer with its bracket
    # knocked off would walk straight through the gate whose whole argument is that it cannot
    # be bypassed.
    assert offending_lines(line), f"an unterminated trailer is no longer flagged: {line!r}"


@pytest.mark.parametrize("line", PUNCTUATED)
def test_punctuation_after_the_address_does_not_disarm_the_trailer_rule(line: str) -> None:
    # The other cost, and the one that shipped broken for a round: a rule reading "anything
    # after `>` is prose" silently missed the canonical harness trailer with a full stop typed
    # after it -- on BOTH the domain rule and the product-name rule. Punctuation is not a word;
    # only a word after the address makes the line a sentence. Kept as a corpus rather than one
    # example so a later narrowing is measured against the whole class it can break.
    assert offending_lines(line), f"a real trailer is no longer flagged: {line!r}"


@pytest.mark.parametrize("line", FOOTERS)
def test_a_real_footer_survives_the_bounded_tail(line: str) -> None:
    # The pair to the three footer-shaped sentences in `NEGATIVES`. Bounding the footer is what
    # stopped `commit strip` amputating a sentence, and the cheap way to bound it -- "the line
    # ends at the vendor word" -- loses every one of these, the canonical harness footer
    # included. Kept as a corpus so a later narrowing is measured against the whole class.
    assert offending_lines(line) == [Offence(1, "generated-with footer")]


def test_strip_does_not_amputate_a_body_sentence_that_begins_with_the_footer_words() -> None:
    """The footer-anchoring defect, end to end: `commit strip` deleting prose before the commit
    exists.

    Measured on the shipped module, which anchored `_FOOTER` at the start of the line only:

        offending: [Offence(3, 'generated-with footer')]
        strip    : 'refactor: rework the exporter\\n'     <- the sentence gone

    Both assertions are the point and neither is read off the subject. The first says the
    sentence is not an offence; the second says the whole message comes back byte for byte,
    which a `strip_message` that removed the line and reported nothing would still fail.
    """
    message = (
        "refactor: rework the exporter\n"
        "\n"
        "Generated with Claude Code and then reviewed by a human.\n"
    )
    assert offending_lines(message) == []
    assert strip_message(message) == message


def test_trailer_shaped_prose_above_the_block_is_not_swallowed_by_the_walk() -> None:
    """The walk's cost, measured and bounded rather than left to be rediscovered.

    A paragraph is reached by the walk when EVERY line in it is an attribution, so a body
    sentence that is itself a full trailer match and stands alone above the harness block
    would be stripped with it. That is what this sentence -- the module's own designated
    example of trailer-shaped prose, from `test_only_the_final_paragraph_is_judged` -- did
    before the trailer value was required to end at its address:

        offending: [Offence(3, trailer), Offence(5, footer), Offence(7, trailer)]
        strip    : 'fix: t\\n'            <- the sentence gone

    Both assertions are the point. The first says the sentence survives; the second says the
    two-paragraph block above it is still removed whole, so this was bought by narrowing what
    counts as a trailer and not by narrowing the walk. What is NOT claimed here: that no body
    line is reachable. One that really is an attribution -- a forbidden trailer pasted as an
    example, alone in its paragraph -- still is, and the module docstring says so.
    """
    message = (
        "fix: t\n"
        "\n"
        "Reviewed-by: Copilot <x@y.z> said nothing useful.\n"
        "\n"
        "\U0001f916 Generated with [Claude Code](https://claude.com/claude-code)\n"
        "\n"
        "Co-Authored-By: Claude <noreply@anthropic.com>\n"
    )
    assert offending_lines(message) == [
        Offence(5, "generated-with footer"),
        Offence(7, "attribution trailer naming an AI tool"),
    ]
    assert strip_message(message) == (
        "fix: t\n\nReviewed-by: Copilot <x@y.z> said nothing useful.\n"
    )


def test_only_the_final_paragraph_is_judged() -> None:
    # Git trailers and harness footers live in the last paragraph; a body sentence that
    # happens to be trailer-shaped is prose, and prose is never a violation.
    body = "fix: t\n\nReviewed-by: Copilot <x@y.z> said nothing useful.\n\nMore body.\n"
    assert offending_lines(body) == []
    tail = "fix: t\n\nMore body.\n\nReviewed-by: GitHub Copilot <copilot@github.com>\n"
    assert offending_lines(tail) == [Offence(5, "attribution trailer naming an AI tool")]
    # THE WALK NEVER STARTS when the last paragraph is body. Measured, not assumed: the two
    # fixtures above stopped proving this the moment a trailer value was required to end at
    # its address, because the sentence in the first is no longer an attribution and the walk
    # then declines to step for the ordinary reason. Deleting the guard that tests the LAST
    # paragraph before stepping left every test in this file green -- a surviving mutant, and
    # the assertion was redesigned rather than the entry reworded. Here the paragraph above
    # the body really is attribution, which is the only shape that tells the two apart.
    above = "fix: t\n\nGenerated with Codex\n\nMore body.\n"
    assert offending_lines(above) == []
    assert strip_message(above) == above


@pytest.mark.parametrize("tail", ["", "\n", "\n   \n", "\n\n\n", "\n\t\n \n"])
def test_a_blank_tail_neither_hides_an_offence_nor_moves_its_line_number(tail: str) -> None:
    # The corpus entries above prove the offence is still found; this pins the other half,
    # which a "did it flag anything" assertion would miss: the reported line number is the
    # offending line's own, not one shifted by however many blanks trail the message.
    message = "fix: thing\n\nBody.\n\nCo-Authored-By: Claude <noreply@anthropic.com>" + tail
    assert offending_lines(message) == [Offence(5, "attribution trailer naming an AI tool")]


def test_the_labels_are_the_three_this_module_publishes() -> None:
    # Against three fixed literals, not against anything `_PATTERNS` produced: the `commit`
    # command renders these labels, so a label edit that forgets the command is a contract
    # break.
    assert ATTRIBUTION_LABELS == (
        "attribution trailer naming an AI tool",
        "generated-with footer",
        "AI-generated marker line",
    )


def test_a_single_line_message_is_its_own_final_paragraph() -> None:
    assert offending_lines("Generated with Codex") == [Offence(1, "generated-with footer")]


def test_an_offence_carries_a_line_number_and_a_label_but_not_the_text() -> None:
    # The message is repository-authored (principle 5); only what this module computed travels.
    message = "fix: thing\n\nBody.\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n"
    assert offending_lines(message) == [Offence(5, "attribution trailer naming an AI tool")]


def test_strip_removes_trailer_and_its_blank_line() -> None:
    message = (
        "feat(food): let a decision select an observation by handle\n"
        "\n"
        "The decision now names the observation it used.\n"
        "\n"
        "Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>\n"
    )
    assert strip_message(message) == (
        "feat(food): let a decision select an observation by handle\n"
        "\n"
        "The decision now names the observation it used.\n"
    )


def test_strip_removes_a_whole_two_paragraph_attribution_block() -> None:
    """The measured defect of the one-paragraph rule, and the reason the walk exists.

    On the shipped module this block half-stripped: `offending_lines` named one offence, the
    trailer, and `strip_message` returned the body *plus* the footer. The hook then printed
    `stripped 1 attribution line(s)` and `commit check` failed the same commit in CI naming
    the footer — so fixing what the developer was told about failed again on re-run.

    Both halves are asserted, against fixed literals rather than against anything the module
    produced: a `strip_message` that removed the block but reported one offence, or one that
    named both and removed one, each passes half of this.
    """
    assert offending_lines(CANONICAL_BLOCK) == [
        Offence(5, "generated-with footer"),
        Offence(7, "attribution trailer naming an AI tool"),
    ]
    assert strip_message(CANONICAL_BLOCK) == (
        "fix: something real\n\nA body paragraph that must survive.\n"
    )


def test_strip_keeps_a_human_co_author() -> None:
    message = (
        "fix: correct the rollover hour\n"
        "\n"
        "Co-authored-by: A Person <person@example.com>\n"
        "Co-Authored-By: Claude <noreply@anthropic.com>\n"
    )
    assert strip_message(message) == (
        "fix: correct the rollover hour\n\nCo-authored-by: A Person <person@example.com>\n"
    )


def test_strip_is_a_noop_on_a_clean_message() -> None:
    message = "docs: record what the handle measures at k=5\n\nNo trailers here.\n"
    assert strip_message(message) == message


def test_prose_about_the_policy_survives() -> None:
    """The rule is discussed in docs and reviews; only trailer-shaped lines are matched."""
    message = (
        "docs: explain why the attribution gate lives in CI\n"
        "\n"
        "A trailer naming the model is added by the harness system prompt, so the gate\n"
        "runs after the message exists rather than competing with that instruction.\n"
    )
    assert not offending_lines(message)


def test_strip_never_touches_the_body() -> None:
    """The source stripped a mid-message trailer and collapsed the gap; here a trailer-shaped
    line above the final paragraph is body text and is left exactly as it is.
    This is the property that stops a prepare-commit-msg hook amputating a sentence.

    The fixture strips something on purpose. With a clean message this passes through the
    `if not doomed: return message` early return and pins nothing at all about the body — it
    was written that way, and it is the doubled blank plus the trailer-shaped body line
    surviving a *real* removal that makes the claim in the name true.
    """
    message = (
        "fix: thing\n"
        "\n"
        "Body text.\n"
        "\n"
        "Reviewed-by: Copilot <x@y.z>\n"
        "\n"
        "\n"
        "More body.\n"
        "\n"
        "Co-Authored-By: Claude <noreply@anthropic.com>\n"
    )
    assert strip_message(message) == (
        "fix: thing\n\nBody text.\n\nReviewed-by: Copilot <x@y.z>\n\n\nMore body.\n"
    )


def test_strip_removes_only_the_offending_line_of_a_mixed_final_paragraph() -> None:
    """A human trailer and a harness footer share the last paragraph; only the footer goes.

    This was first written as `test_strip_collapses_the_blank_a_removed_trailer_leaves`, renamed
    to what it actually pins: no blank is collapsed here, and none ever can be by this shape.
    Offences only occur inside the final paragraph, which by construction contains no blank
    line, so removing one can never bring two blanks together — the only blank a removal leaves
    is the one *before* the paragraph, and that is the tail the pop in `strip_message` handles
    and `test_strip_removes_trailer_and_its_blank_line` pins. The collapse branch is reachable
    only from a message that already held a doubled blank; the test below is that one.
    """
    message = "fix: thing\n\nBody.\n\nSigned-off-by: Me <me@example.com>\nGenerated with Codex\n"
    assert strip_message(message) == "fix: thing\n\nBody.\n\nSigned-off-by: Me <me@example.com>\n"


def test_strip_leaves_a_doubled_blank_in_the_body_alone() -> None:
    """A strip is not a reformat: a doubled blank the author left in the body survives it.

    The first cut collapsed blank runs across the whole message once anything was removed, so
    a strip silently reflowed a body the author had spaced on purpose — and the docstring
    claimed the opposite. Its mutation is restoring that message-wide collapse: the doubled
    blank below then comes back single. Hand-measured rather than declared in `mutations/`,
    because the change is a multi-line rewrite rather than one substituted line.
    """
    message = "fix: thing\n\nBody.\n\n\nSigned-off-by: Me <me@example.com>\nGenerated with Codex\n"
    assert strip_message(message) == (
        "fix: thing\n\nBody.\n\n\nSigned-off-by: Me <me@example.com>\n"
    )


def test_a_message_that_is_only_attribution_strips_to_nothing() -> None:
    """The empty result `commit strip` has to notice rather than write back.

    Writing it back aborts the commit with git's confusing "empty message" error, so the
    command leaves the file alone and lets the range check explain instead. Pinned here
    because that decision is only safe while this function really does return the empty
    string; its mutation is the tail of `strip_message`, where returning a bare newline
    instead of `""` reddens this test alone.
    """
    assert strip_message("Generated with Codex\n") == ""


# Lines the rules took in time more than linear in their length, each followed by a trailer as
# the message's last line, so the answer says the long line was judged and read past. A message
# reaches these rules in the `prepare-commit-msg` hook and in CI's `commit check`, whatever its
# author wrote. Each line is sized so that the old reading takes over an hour and a linear one a
# fraction of a second; the last field says whether the line is itself an offence.
LONG_LINES = {
    # A trailer's value read by a lazy pattern ended by blanks, which scanned the blanks again
    # from every character of the value: 116 s over 160,000 blanks.
    "trailer blanks": ("Co-Authored-By: Claude", " ", 1 << 20, " <noreply@anthropic.com>", True),
    # A footer-shaped line that goes on into prose, its words read as a choice to backtrack over:
    # `A1` is both a name word and a version, which doubled the work at each one, 7 s at 24 of
    # them; and every slash given back rescanned the rest of the line, 1.6 s at 16,000.
    "footer words": ("Generated with Claude", " A1", 64, " and then by hand", False),
    "footer slashes": ("Generated with Claude", " /", 1 << 19, " and then by hand", False),
}
_TRAILER_LABEL = ATTRIBUTION_LABELS[0]
_LONG_LINE_PROBE = (
    "import sys\n"
    "from stayfixed.guards.commit import offending_lines\n"
    "head, unit, count, tail = sys.argv[1:]\n"
    "line = head + unit * int(count) + tail\n"
    "last = 'Co-Authored-By: Claude <noreply@anthropic.com>'\n"
    "print(offending_lines(f'fix: a thing\\n\\n{line}\\n{last}'))\n"
)
# The child's bound: far below what the old reading took of each line above on a laptop, and a
# hundred times what the linear one takes there, start-up included, so neither load nor a fast
# machine moves a case across it.
_LONG_LINE_SECONDS = 30


@pytest.mark.parametrize("shape", sorted(LONG_LINES))
def test_a_long_message_line_is_judged_in_time_linear_in_its_length(shape: str) -> None:
    # In a child under a timeout, so a regression fails this case rather than holding a worker.
    # Mutations (oracle): `mutations/`'s "a trailer's value is found by a lazy match" ->
    # `trailer blanks`; "a footer's words are given back to be read again" -> `footer words` and
    # `footer slashes`.
    head, unit, count, tail, offends = LONG_LINES[shape]
    try:
        done = subprocess.run(
            [sys.executable, "-c", _LONG_LINE_PROBE, head, unit, str(count), tail],
            capture_output=True,
            text=True,
            timeout=_LONG_LINE_SECONDS,
            check=False,
        )
    except subprocess.TimeoutExpired:
        pytest.fail(f"the commit-message rules ran past {_LONG_LINE_SECONDS} s on one long line")
    judged = [Offence(3, _TRAILER_LABEL)] if offends else []
    assert done.stdout == f"{[*judged, Offence(4, _TRAILER_LABEL)]}\n", done.stderr


# Trailers whose rules held a record of match state per label of an address, or per word of a
# model's name, when `re` kept one for each pass it might give back: 124 MiB more over a million of
# either. Each is an offence, and is followed by a trailer as the message's last line, as above.
LONG_TRAILERS = {
    "address labels": ("Co-Authored-By: A Bot <noreply@", "a.", 1 << 20, "anthropic.com>"),
    "model words": ("Co-Authored-By: Claude Opus", " a", 1 << 20, " <bot@example.org>"),
}
# The most the child may grow its peak resident size by while judging one of them: a few copies of
# the two-mebibyte line, a quarter of that record.
_LONG_TRAILER_BYTES = 32 << 20


@pytest.mark.parametrize("shape", sorted(LONG_TRAILERS))
def test_a_long_trailer_is_judged_in_memory_linear_in_its_length(shape: str) -> None:
    # The child measures its own peak resident size before and after (`ru_maxrss`, bytes on macOS
    # and KiB on Linux), under a timeout. Mutations (oracle): `mutations/`'s "an address's labels
    # are read by a pattern that gives them back" -> `address labels`; "a model's version words
    # are given back" -> `model words`.
    probe = (
        "import resource, sys\n"
        "from stayfixed.guards.commit import offending_lines\n"
        "head, unit, count, tail = sys.argv[1:]\n"
        "line = head + unit * int(count) + tail\n"
        "last = 'Co-Authored-By: Claude <noreply@anthropic.com>'\n"
        "scale = 1 if sys.platform == 'darwin' else 1024\n"
        "before = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss\n"
        "judged = offending_lines(f'fix: a thing\\n\\n{line}\\n{last}')\n"
        "grown = (resource.getrusage(resource.RUSAGE_SELF).ru_maxrss - before) * scale\n"
        "print(grown, judged)\n"
    )
    head, unit, count, tail = LONG_TRAILERS[shape]
    try:
        done = subprocess.run(
            [sys.executable, "-c", probe, head, unit, str(count), tail],
            capture_output=True,
            text=True,
            timeout=_LONG_LINE_SECONDS,
            check=False,
        )
    except subprocess.TimeoutExpired:
        pytest.fail(f"the commit-message rules ran past {_LONG_LINE_SECONDS} s on one trailer")
    grown, judged = done.stdout.split(maxsplit=1)
    assert judged == f"{[Offence(3, _TRAILER_LABEL), Offence(4, _TRAILER_LABEL)]}\n", done.stderr
    assert int(grown) < _LONG_TRAILER_BYTES, f"the rules grew the peak by {int(grown) >> 20} MiB"


CONFIG = """
[stayfixed]
version = "0.1.0"
state = "installed"
preset = "recommended"
profile = ""
agents = ["claude"]

[project]
name = "widget"
base_branch = "main"
release_branch = "main"
"""


def repo(tmp_path: Path, *messages: str) -> Path:
    root = tmp_path / "repo"
    root.mkdir()
    git(root, "init", "-q", "-b", "main")
    (root / CONFIG_FILE).write_text(CONFIG, encoding="utf-8")
    git(root, "add", "-A")
    git(root, "commit", "-q", "-m", "chore: seed")
    git(root, "tag", "base")
    for index, message in enumerate(messages):
        (root / f"f{index}.txt").write_text("x\n", encoding="utf-8")
        git(root, "add", "-A")
        git(root, "commit", "-q", "-m", message)
    return root


@needs_git
def test_check_range_reports_each_offending_commit_once(tmp_path: Path) -> None:
    root = repo(
        tmp_path,
        "feat: clean",
        "fix: dirty\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n",
        "Fixed without a type, which is not this command's business",
    )
    report = check_range(root, "base..HEAD", load(root, machine=tmp_path / "absent.toml"))
    assert report.commits == 3
    labels = [(v.offences[0].line, v.offences[0].label) for v in report.violations]
    assert labels == [(3, "attribution trailer naming an AI tool")]
    # The sha, asked of git rather than read back off the report: without this the violation
    # could name any of the three commits and nothing here would notice, which is the whole
    # value of the report to someone rewriting a message.
    dirty = git(root, "rev-parse", "HEAD~1").strip()
    assert [violation.sha for violation in report.violations] == [dirty]


@needs_git
def test_every_offence_of_one_commit_travels_in_its_violation(tmp_path: Path) -> None:
    # `check_range` fans a commit's offences into one `Violation`; with only single-offence
    # fixtures, `tuple(offences[:1])` would pass everything else in this file.
    root = repo(
        tmp_path,
        "fix: two\n\nCo-Authored-By: Claude <noreply@anthropic.com>\nGenerated with Codex\n",
    )
    report = check_range(root, "base..HEAD", load(root, machine=tmp_path / "absent.toml"))
    assert len(report.violations) == 1
    assert report.violations[0].offences == (
        Offence(3, "attribution trailer naming an AI tool"),
        Offence(4, "generated-with footer"),
    )


@needs_git
def test_check_range_honours_the_attribution_switch(tmp_path: Path) -> None:
    root = repo(tmp_path, "fix: dirty\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n")
    (root / CONFIG_FILE).write_text(
        CONFIG + "\n[commit_messages]\nattribution_check = false\n", encoding="utf-8"
    )
    report = check_range(root, "base..HEAD", load(root, machine=tmp_path / "absent.toml"))
    assert report.violations == ()
    # The contract is that the report still says how much it read: `return Report(0, ())`
    # satisfies the line above and would hand the command a silent, empty, plausible answer.
    assert report.commits == 1


@needs_git
def test_an_empty_range_is_zero_commits_not_an_error(tmp_path: Path) -> None:
    root = repo(tmp_path)
    assert commits_in(root, "base..HEAD") == []


@needs_git
def test_a_control_byte_in_a_body_does_not_split_the_commit_into_two_records(
    tmp_path: Path,
) -> None:
    """One `\\x01` in a body voided the gate for that commit. Measured, not foreseen.

    `%x01` was the record separator, chosen for "neither can occur in a commit message". NUL
    cannot; `\\x01` can, and git stores it. On the shipped module this fixture measured:

        commits_in returned 2 record(s) for one commit
          sha='5bf5be35eaab'  offences=[]
          sha=' in it.\\n\\nCo-'  offences=[]

    The record split, the remainder of the message landed in the field read as a `sha`, the
    count went 1 -> 2 and the trailer travelled in a record nothing judged. Both assertions are
    needed: a reader that returned one record holding only the text before the `\\x01` would
    satisfy the count and still miss the trailer.

    `--cleanup=verbatim` is what gets the byte past `git commit`'s own message cleanup; it is
    not exotic, it is the mode `-F` with a prepared file is routinely used in.
    """
    root = repo(tmp_path)
    message = (
        "fix: sneaky\n"
        "\n"
        "A body line carrying \x01 in it.\n"
        "\n"
        "Co-Authored-By: Claude <noreply@anthropic.com>\n"
    )
    path = tmp_path / "msg"
    path.write_text(message, encoding="utf-8")
    (root / "sneaky.txt").write_text("x\n", encoding="utf-8")
    git(root, "add", "-A")
    git(root, "commit", "-q", "--cleanup=verbatim", "-F", str(path))

    commits = commits_in(root, "base..HEAD")
    assert len(commits) == 1
    assert commits[0].sha == git(root, "rev-parse", "HEAD").strip()
    assert offending_lines(commits[0].message) == [
        Offence(5, "attribution trailer naming an AI tool")
    ]


def test_a_range_shaped_like_an_option_is_refused_before_git_sees_it(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # A value that reaches a subprocess in an option's position is untrusted. `--all` is the
    # whole-history sweep the source had; `--output=/tmp/x` is what the refusal exists for.
    import subprocess as sp

    def forbidden(*args: object, **kwargs: object) -> object:
        raise AssertionError("git was run")

    monkeypatch.setattr(sp, "run", forbidden)
    with pytest.raises(Refusal):
        commits_in(tmp_path, "--output=/tmp/x")


@needs_git
def test_a_range_git_cannot_read_is_a_refusal_not_a_finding(tmp_path: Path) -> None:
    root = repo(tmp_path)
    with pytest.raises(Refusal):
        commits_in(root, "no-such-ref..HEAD")


@needs_git
def test_a_message_git_prints_in_bytes_that_are_not_text_is_a_refusal_not_a_traceback(
    tmp_path: Path,
) -> None:
    # A commit object carries its own `encoding` header, and git re-encodes a message to UTF-8
    # on output only from an encoding it knows. One naming none it knows prints the body raw,
    # and `text=True` decoded it strictly: `UnicodeDecodeError`, a `ValueError`, escaped as an
    # internal error — from a commit anyone can push in a pull request. A refusal like the
    # other ways the log fails, and it quotes none of the message. Mutation (declared): drop
    # the `UnicodeDecodeError` arm — the error escapes and this reddens.
    root = repo(tmp_path)
    tree = git(root, "rev-parse", "HEAD^{tree}").strip()
    parent = git(root, "rev-parse", "HEAD").strip()
    raw = tmp_path / "commit-object"
    raw.write_bytes(
        f"tree {tree}\nparent {parent}\n".encode()
        + b"author t <t@example.com> 1 +0000\ncommitter t <t@example.com> 1 +0000\n"
        + b"encoding x-no-such-encoding\n\nfix: caf\xe9\n"
    )
    crafted = git(root, "hash-object", "-t", "commit", "-w", str(raw)).strip()
    git(root, "update-ref", "refs/heads/main", crafted)
    with pytest.raises(Refusal, match="not UTF-8 text") as caught:
        commits_in(root, "base..HEAD")
    assert "caf" not in str(caught.value)


@pytest.mark.parametrize(
    "failure", [OSError("git is not on PATH"), subprocess.TimeoutExpired("git", 60)]
)
def test_a_git_that_cannot_run_or_times_out_is_a_refusal(
    monkeypatch: pytest.MonkeyPatch, failure: Exception
) -> None:
    # The other two of the three ways the log fails; the non-zero exit is the test above.
    # Letting either escape would reach the CLI as an unhandled error rather than as an exit-2
    # refusal, and a caller reads "the command crashed" very differently from "refused".
    import subprocess as sp

    def explode(*args: object, **kwargs: object) -> object:
        raise failure

    monkeypatch.setattr(sp, "run", explode)
    with pytest.raises(Refusal):
        commits_in(Path("/nowhere"), "a..b")


def test_the_log_is_bounded_scrubbed_and_terminated(monkeypatch: pytest.MonkeyPatch) -> None:
    """The three properties of the one `git` this module runs, each asserted where it can fail.

    A bound, a scrubbed environment and a closed argument list are all invisible to a test that
    only checks the return value: deleting any of the three leaves every other test in this
    file green.
    """
    import subprocess as sp

    seen: dict[str, object] = {}
    argv_seen: list[str] = []

    def fake(argv: list[str], **kwargs: object) -> sp.CompletedProcess[bytes]:
        seen.update(kwargs)
        argv_seen.extend(argv)
        return sp.CompletedProcess(argv, 0, stdout=b"", stderr=b"")

    # A `GIT_DIR` the session happens to carry makes git answer for a different repository
    # than the one the range is about; `scrubbed_env` is what drops it. Outside a hook, where
    # `git_run` hands git this process's own `PATH`, so the expected environment is the plain
    # scrubbed one and no `git` on this machine is needed to reach `fake`.
    launched_by_the_hook_wrapper(monkeypatch, False)
    monkeypatch.setenv("GIT_DIR", "/elsewhere/.git")
    monkeypatch.setattr(sp, "run", fake)
    # The bound is read below `git_run`, where the suite's floor has already lifted it: at the
    # product's zero, or a dropped `timeout=` would reach `fake` as the floor and pass.
    monkeypatch.delenv(gitenv.FLOOR_VARIABLE)
    assert commits_in(Path("/nowhere"), "a..b") == []

    # `seen["timeout"] == LOG_TIMEOUT_SECONDS` alone is an expectation read from the subject
    # under test: both sides move together, so it survives every edit to the constant and
    # reddens only when `timeout=` is dropped entirely. The fixed literal is its pair.
    assert seen["timeout"] == LOG_TIMEOUT_SECONDS
    assert LOG_TIMEOUT_SECONDS == 60

    env = seen["env"]
    assert isinstance(env, dict)
    assert "GIT_DIR" not in env
    assert env == gitenv.scrubbed_env()

    # `--` last, and the range before it: without the terminator a range that names an
    # existing file is read as a pathspec and the log silently answers about something else.
    assert argv_seen[-2:] == ["a..b", "--"]
