"""The generated index: a pure function of the entry files, and the refusal that keeps
regenerating it from destroying what only it holds.
"""

from __future__ import annotations

import posixpath
import re
from pathlib import Path, PurePosixPath

from stayfixed.config.paths import contained
from stayfixed.errors import Refusal
from stayfixed.identifiers import Identifiers
from stayfixed.ledger.entries import Entry, entry_dir, read_ledger_text
from stayfixed.ledger.register import Register, Section

# Structural recognition: the first paragraph opens with the marker's fixed prefix and names
# `index` inside the backticks. This also recognises the generator this one replaced, whose
# sentence differed only in the invocation.
_GENERATED = re.compile(r"\A_Generated by `[^`\n]*\bindex\b[^`\n]*` from ")
_SECTION_COUNT = re.compile(r"\A## (.+) \(\d+\)\Z")
# The two refusals, as format strings: `refuse_index_overwrite` raises them and `check.problems`
# reports them, and both must describe the same file the same way (`bugs`, `index`, `count`,
# `first` are the fields).
ENTRIES_MISSING = (
    "{bugs}/ does not exist, but {index} is this tool's generated index; the entry files are "
    "the ledger and the index carries nothing of its own, so restore them rather than "
    "regenerating over it"
)
# `{first!r}` is repository-authored text inside a `Refusal` message, and deliberately so: this
# message reaches the terminal of the person who ran the command against their own repository,
# which is the one reader the rule permits, and quoting the line is what makes the refusal
# actionable — without it the operator is told a line exists but not which.
FOREIGN_CONTENT = (
    "{index} carries {count} line(s) this tool did not generate, the first being {first!r}; "
    "the index is rendered from the entry files alone, so that content exists nowhere else — "
    "recover it before regenerating"
)


def _relative(register: Register, target: str) -> str:
    """`target` (a root-relative config path) as a link from the index's own directory."""
    index_dir = str(PurePosixPath(register.index).parent)
    return posixpath.relpath(target, index_dir)


def generated_by(register: Register) -> str:
    """The marker the index's first paragraph opens with, naming the command that writes it."""
    return f"_Generated by `stayfixed {register.name} index`"


def header(register: Register) -> str:
    """The title and the marker paragraph, which links the runbook and the audits directory
    each where the register declares one."""
    directory = _relative(register, register.directory)
    marker = (
        f"{generated_by(register)} from `{directory}/{register.ids.prefix}-*.md`; edit the entry\n"
        "files, not this one."
    )
    if register.runbook is not None:
        marker += (
            " How to file, close and reference an entry:\n"
            f"[runbook]({_relative(register, register.runbook)})."
        )
    if register.audits is not None:
        # Appended to the directory's own link rather than linked on its own: where the ledger
        # directory is the index's directory that link is `.`, and its `./audits/` is what every
        # index already committed for such a layout carries.
        marker += (
            f" Audit provenance: [{register.directory}/{register.audits}/]"
            f"({directory}/{register.audits}/)."
        )
    return f"# {register.title}\n\n{marker}_\n"


def _columns(section: Section) -> str:
    """A section's table head: the column headings, then the separator line."""
    headings = " | ".join(heading for heading, _ in section.columns)
    return f"| {headings} |\n|{'---|' * len(section.columns)}\n"


def _column_lines(register: Register) -> frozenset[str]:
    """The table lines the generator writes that carry no identifier, so are judged by shape
    alone. Taken from the blocks `render_index` writes rather than respelled, because a column
    heading this set did not know about would be classified as a row with no entry behind it and
    refuse the regeneration of an index nobody had touched."""
    return frozenset(
        line for section in register.schema.sections for line in _columns(section).splitlines()
    )


def index_path(root: Path, register: Register) -> Path:
    return contained(root, register.index)


def index_text(root: Path, register: Register) -> str:
    """The committed index's text, or `""` where there is no index yet.

    An index that exists but cannot be read is not the same thing as one that is absent, and
    answering `""` for it would say the ledger is uninitialised and pass `check` over a tree
    nobody has looked at. `read_ledger_text` makes it a `LedgerError` naming the file, so it
    reaches the operator as findings (exit 1) rather than as an internal error (exit 2).
    """
    path = index_path(root, register)
    return read_ledger_text(path, where=Path(register.index)) if path.is_file() else ""


def _cell(text: str) -> str:
    """Keep a value inside its table cell: `|` would end the column, a newline the row.

    The backslash is escaped first, and it has to be: escaping only the pipe renders a title
    containing `\\|` as an escaped backslash followed by a live separator, which gives that row
    one column more than its header and slides the Found date under the wrong heading. Both
    readers of the index share this escaper, so the staleness check sees nothing wrong with it.
    """
    return text.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ").strip()


def _link(entry: Entry, register: Register) -> str:
    return f"[{entry.id}]({_relative(register, register.directory)}/{entry.id}.md)"


def _row(entry: Entry, section: Section, register: Register) -> str:
    cells = (
        _link(entry, register) if key == "id" else _cell(entry.value(key))
        for _, key in section.columns
    )
    return f"| {' | '.join(cells)} |\n"


def render_index(entries: list[Entry], register: Register) -> str:
    """The whole of the index file, from the entry files alone.

    Rows appear in the order `entries` arrives in, grouped into the schema's sections by status
    — the numeric ordering is `load_entries`' guarantee, not this function's, and every caller
    here goes through it. Nothing about the index is stored: it is a pure function of the entry
    files, which is what lets the staleness check decide by rendering and comparing.
    """
    parts = [header(register)]
    for section in register.schema.sections:
        selected = [e for e in entries if e.status in section.statuses]
        parts.append(f"\n## {section.heading} ({len(selected)})\n\n")
        parts.append(_columns(section))
        parts.extend(_row(e, section, register) for e in selected)
    return "".join(parts)


def is_generated_index(text: str) -> bool:
    """Whether this index is one this tool wrote, rather than a hand-written ledger."""
    lines = text.splitlines()
    if not lines or not lines[0].startswith("# "):
        return False
    start = 1
    while start < len(lines) and not lines[start].strip():
        start += 1
    end = start
    while end < len(lines) and lines[end].strip():
        end += 1
    return _GENERATED.match("\n".join(lines[start:end])) is not None


def _generated_header_lines(text: str) -> list[str]:
    """The title and the first paragraph, when that paragraph is this tool's marker; else [].

    Recognised by structure rather than by matching `header()` literally: the `# ` title line
    and the first paragraph under it, which has to carry the generator marker. Both are
    rewritten by every regeneration, so a difference there loses nothing that is not also in
    this module — while reading them literally made any future edit to the header's prose turn
    every committed index into content "this tool did not generate", refusing the regeneration
    with `recover it before regenerating` about the one text in that file whose home is
    `header()` above, and pointing away from the fix. A reworded header is now what it is: a
    stale index, whose remedy is the regeneration.

    Deliberately just those: the title and that one paragraph. A line an operator added below
    them is separated by the blank line that ends the paragraph, so it stays foreign — which is
    the content the guard exists for, and the property this must not trade away.
    """
    if not is_generated_index(text):
        return []
    lines = text.splitlines()
    start = 1
    while not lines[start].strip():
        start += 1
    end = start
    while end < len(lines) and lines[end].strip():
        end += 1
    return [lines[0], *lines[start:end]]


def _entry_identifiers(root: Path, register: Register) -> set[str]:
    """The identifiers the ledger directory actually holds a file for.

    Read as filenames and never parsed. This is asked from inside a guard whose whole job is to
    run before a destructive write, so a sibling entry that would not parse must not be able to
    turn it off; an absent ledger directory answers the empty set, which makes every row foreign
    and is the fail-closed answer.
    """
    ids = register.ids
    return {
        path.stem
        for path in entry_dir(root, register).glob(f"{ids.prefix}-*.md")
        if ids.is_identifier(path.stem)
    }


def _row_identifier(line: str, ids: Identifiers) -> str:
    """The identifier a table row's first cell links, or `""` for a row naming none.

    The first cell is `_link`'s output and carries no `|` of its own, so splitting on the
    separator finds it whatever a later cell's escaped pipe does to the rest of the row.
    """
    cells = line.split("|")
    found = ids.mention.search(cells[1]) if len(cells) > 1 else None
    return found.group(0) if found is not None else ""


def foreign_index_lines(root: Path, text: str, register: Register) -> list[str]:
    """Every line of the committed index outside the grammar `render_index` writes.

    That grammar is the whole of what an index may hold: the header, one `## <Heading> (N)` per
    section, table headers and `| … |` rows, and blank lines. The regeneration renders the file
    from the entry files alone, so anything else in it lives only there and that write deletes
    it — with no diff, no prompt, and exit 0.

    Asked as line shapes rather than as a re-render, because "does regenerating destroy
    something" is a different question from "is this index current". A stale generated index
    destroys nothing and its remedy is to regenerate; a heading with two spaces after its
    `##`, a `###` one, and a prose section with no identifier at all survive nowhere else.
    Those shapes are spelled out in this guard's own tests, not here: writing one down in a
    scanned root would make this comment the dangling reference the scan exists to catch.

    **A row is judged by what stands behind it, not by its shape.** Accepting any line opening
    with `|` made a row the only surviving record of a bug — an entry file deleted in a merge,
    or a whole hand-written section of them — indistinguishable from one the generator wrote,
    which is exactly the loss `refuse_index_overwrite`'s docstring names and the one
    `ENTRIES_MISSING` cannot see, because that fires only when the entire ledger directory is
    gone. `bugs check` then reported `stale-index; run: stayfixed bugs index`, and that command
    deleted the record. So each row's identifier is resolved against the entry files, and a row
    with no entry behind it — or none naming an identifier at all — is foreign. The column
    headings carry no identifier and are generated, so they stay allowed by shape.
    """
    allowed = set(header(register).splitlines()) | set(_generated_header_lines(text))
    headings = {section.heading for section in register.schema.sections}
    column_lines = _column_lines(register)
    present = _entry_identifiers(root, register)
    ids = register.ids
    foreign: list[str] = []
    for line in text.splitlines():
        if not line.strip() or line in allowed:
            continue
        if line.startswith("|"):
            if line in column_lines or _row_identifier(line, ids) in present:
                continue
            foreign.append(line)
            continue
        counted = _SECTION_COUNT.match(line)
        if counted is not None and counted.group(1) in headings:
            continue
        foreign.append(line)
    return foreign


def refuse_index_overwrite(root: Path, register: Register, current: str) -> None:
    """Refuse to regenerate while that write would destroy something.

    The regeneration renders the index from the entry files alone, so anything the committed
    file holds of its own is deleted by that write — with no diff to review, no prompt, and
    exit 0. In a merge whose operator resolved the index to the wrong side it is whichever
    sections only that side carried; it is unrecoverable once the merge is committed, and
    filing a bug reaches the same write, so `bugs new` must not be what destroys the ledger
    either.

    Two refusals: entry files that have vanished from under a generated index name their own
    restoration, and anything else outside the generated grammar can only be recovered by
    hand. Neither names a command, because the regeneration is the destruction rather than
    the repair.
    """
    index = register.index
    if not entry_dir(root, register).is_dir() and is_generated_index(current):
        raise Refusal(ENTRIES_MISSING.format(bugs=register.directory, index=index))
    foreign = foreign_index_lines(root, current, register)
    if foreign:
        raise Refusal(FOREIGN_CONTENT.format(index=index, count=len(foreign), first=foreign[0]))
