"""The machine ledger every scaffolded artifact is recorded in.

The manifest is committed, so `upgrade` and `uninstall` work for a collaborator who never ran
`init`. It is also the only reason `skip_modified` can exist: without a recorded hash there is
no way to tell a file the tool wrote from a file a person wrote, and every refresh would be
either a clobber or a no-op. It carries a `format` so a later migration can key on it, and it
is written atomically, because it is the one file whose corruption bricks both `upgrade` and
`uninstall`.

Its own path is repository-controlled too. `.stayfixed` is an ordinary directory entry that a
repository may commit as a symlink, and a clone materialises one, so both ends of the ledger
go through `contained()` first: otherwise `write` hands the records — content and all — to
whatever the link points at, and `read` takes its idea of what stayfixed owns from there.

`contained()` catches a *committed* symlink and not the race the engine exists to survive — a
component that becomes a link after the check passed. So the write goes through
`fsops.write_within`, the same `O_NOFOLLOW` walk every scaffolded artifact is written through.
It did not, and that was the gap worth naming: every file a user can shrug at was written
through a descriptor, while the one file whose corruption bricks both `upgrade` and
`uninstall` was written by re-resolved string path — `mkdir(parents=True)` following symlinks
and `mkstemp` plus `os.replace` on the name. The strongest protection was applied to the least
valuable targets.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass
from enum import StrEnum
from pathlib import Path

from stayfixed.config.paths import contained
from stayfixed.errors import Refusal
from stayfixed.fsops import UnsafePath, read_regular_text, said, write_within
from stayfixed.jsonobject import json_object

MANIFEST_PATH = Path(".stayfixed") / "manifest.json"
FORMAT = 1

GENERATED = (
    "Generated by stayfixed; do not hand-edit. Removing a record makes `upgrade` treat the "
    "file as foreign and `uninstall` leave it behind."
)


class ManifestError(Refusal):
    """A manifest that cannot be trusted: unreadable, malformed, or carrying unknown values."""


class Kind(StrEnum):
    TEMPLATE = "template"
    MANAGED_REGION = "managed-region"
    KEYED_ENTRIES = "keyed-entries"
    ONCE = "once"


class Location(StrEnum):
    REPO = "repo"
    LOCAL = "local"


@dataclass(frozen=True)
class Record:
    """One artifact as the run that wrote it left it.

    `template` is where the bytes came from, and it carries **two namespaces**. `<area>/<name>`
    names a file the wheel ships and `read` can open — `project/roadmap.md`. `computed/<id>` says
    there is no shipped file at all and the bytes were built by the area: `project.templates`
    spells it `COMPUTED` and uses it for the rendered `stayfixed.toml`, the empty bug index and the
    ignore block. Nothing reads the field yet; `upgrade` is the command that will, and the choice is
    recorded here rather than left for it to rediscover, because the manifests it will read are
    being committed now. A reader tells "built" from "shipped" without asking the wheel, and no
    record claims a file that is not there — which is what three of them did until `7f5a007`.
    """

    id: str
    kind: Kind
    location: Location
    target: str
    template: str
    version: str
    sha256: str


def digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _record_from(raw: object, key: str) -> Record:
    if not isinstance(raw, dict):
        raise ManifestError(f"artifact {key!r} is not a table")
    try:
        kind = Kind(raw["kind"])
        location = Location(raw["location"])
        return Record(
            id=str(raw["id"]),
            kind=kind,
            location=location,
            target=str(raw["target"]),
            template=str(raw["template"]),
            version=str(raw["version"]),
            sha256=str(raw["sha256"]),
        )
    except ValueError as exc:
        raise ManifestError(f"artifact {key!r}: {exc}") from exc
    except KeyError as exc:
        raise ManifestError(f"artifact {key!r} is missing {exc.args[0]!r}") from exc


def _contained_path(root: Path) -> Path:
    """`root/.stayfixed/manifest.json`, refused when anything redirects it out of the root.

    The guard lives here rather than at each call site because this module owns
    `MANIFEST_PATH`: nothing else knows where the ledger lives, so nothing else can be asked
    to remember to check it. `read` consumes the returned path; `write` uses it only for the
    verdict, and then writes through the walk instead of through the string.
    """
    return contained(root, str(MANIFEST_PATH))


@dataclass(frozen=True)
class Manifest:
    records: dict[str, Record]
    format: int = FORMAT

    @classmethod
    def read(cls, root: Path) -> Manifest:
        path = _contained_path(root)
        if not path.is_file():
            return cls({})
        # The file is tracked, so a clone chooses every way it can fail to read: its size too, so
        # it is read to the read cap (`fsops.read_regular_text`), and a fault is said without the
        # path it was opened by. Bytes that are not UTF-8 fail in the decode, before the parser
        # runs. The parse goes through `jsonobject`, which answers JSON nested past the parser and
        # an integer longer than it converts in words of its own: quoting those exceptions told the
        # owner of a committed ledger to raise an interpreter limit, or reported the parser's
        # stack.
        try:
            text = read_regular_text(path)
        except OSError as exc:
            raise ManifestError(f"{MANIFEST_PATH} cannot be read ({said(exc)})") from exc
        except UnicodeDecodeError:
            raise ManifestError(f"{MANIFEST_PATH} is not UTF-8 text") from None
        raw = json_object(text, str(MANIFEST_PATH), error=ManifestError)
        version = raw.get("format", FORMAT)
        # Damage, not a newer stayfixed: `null`, `"1"`, `0` and the rest are no format any
        # stayfixed writes, and "upgrade the plugin" is the wrong remedy for them. `bool` is an
        # `int` to `isinstance`, and no format either.
        if not isinstance(version, int) or isinstance(version, bool) or version < 1:
            raise ManifestError(f"{MANIFEST_PATH}: 'format' is not a positive integer")
        if version > FORMAT:
            raise ManifestError(
                f"{MANIFEST_PATH} was written by a newer stayfixed (format {version!r}); "
                "upgrade the plugin rather than editing it"
            )
        artifacts = raw.get("artifacts", {})
        if not isinstance(artifacts, dict):
            raise ManifestError(f"{MANIFEST_PATH}: 'artifacts' is not an object")
        return cls({key: _record_from(value, key) for key, value in artifacts.items()}, version)

    def write(self, root: Path) -> Path:
        """Replace the ledger through the `O_NOFOLLOW` walk, and refuse rather than raise.

        `contained()` first, for the verdict a user can act on and for the committed-symlink
        case; `write_within` then, so no component of the path is resolved a second time
        between the two. An `OSError` here is a `ManifestError` — this file is written from
        `apply`'s `finally`, and a bare traceback out of that would take the report of what was
        already written with it.
        """
        path = _contained_path(root)
        body = {
            "_generated": GENERATED,
            "format": FORMAT,
            "artifacts": {key: asdict(self.records[key]) for key in sorted(self.records)},
        }
        try:
            write_within(root, str(MANIFEST_PATH), json.dumps(body, indent=2) + "\n")
        except UnsafePath as exc:
            raise ManifestError(f"{MANIFEST_PATH} cannot be written: {exc}") from exc
        except OSError as exc:
            raise ManifestError(f"{MANIFEST_PATH} cannot be written: {exc}") from exc
        return path

    def get(self, artifact_id: str) -> Record | None:
        return self.records.get(artifact_id)

    def with_record(self, record: Record) -> Manifest:
        return Manifest({**self.records, record.id: record}, self.format)

    def without(self, ids: frozenset[str]) -> Manifest:
        return Manifest({k: v for k, v in self.records.items() if k not in ids}, self.format)
