"""The ledger engine serves any register, and the bug ledger is one value of it, byte for byte.

The two literals below were captured from the engine before it took a register, and are not
derived from the code under test: every project's manifest records the empty index's digest, so
a change to those bytes is an upgrade every project sees, not a refactor.

stayfixed:ledger:fixtures — the identifiers below are sample data, not claims about a ledger.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

from stayfixed.config.loader import load, preset_defaults
from stayfixed.errors import StayfixedError
from stayfixed.identifiers import Identifiers
from stayfixed.ledger import write
from stayfixed.ledger.entries import load_entries
from stayfixed.ledger.index import render_index
from stayfixed.ledger.register import Register, Schema, Section, bug_register
from stayfixed.ledger.write import Allocation, file_entry
from stayfixed.project.api import project_templates
from stayfixed.release.api import Resolution

CONFIG = """
[stayfixed]
version = "0.1.0"
state = "installed"
preset = "recommended"
profile = ""
agents = ["claude"]

[project]
name = "widget"
base_branch = "main"
release_branch = "main"
"""

# One entry per status, with a title that exercises the cell escaper and a fixed-in value that
# needs quoting, so the capture below pins every column layout and both escapes.
BUG_FIXTURE = {
    "BR-001.md": (
        '---\nid: BR-001\ntitle: "a pipe | and a backslash \\\\ in a title"\nstatus: open\n'
        "severity: high\narea: ledger\nfound: 2026-01-02\nsource:\nfixed_in:\nrelated: [BR-004]\n"
        "---\n\nbody\n"
    ),
    "BR-002.md": (
        "---\nid: BR-002\ntitle: half done\nstatus: partial\nseverity: medium\narea: hooks\n"
        "found: 2026-01-03\nsource: a review\nfixed_in:\nrelated:\n---\n\nbody\n"
    ),
    "BR-003.md": (
        "---\nid: BR-003\ntitle: not a bug\nstatus: rejected\nseverity: low\narea: docs\n"
        "found: 2026-01-04\nsource:\nfixed_in:\nrelated:\n---\n\nbody\n"
    ),
    "BR-004.md": (
        "---\nid: BR-004\ntitle: repaired\nstatus: fixed\nseverity: high\narea: ledger\n"
        'found: 2026-01-05\nsource:\nfixed_in: "`abc1234`"\nrelated: [BR-001]\n---\n\nbody\n'
    ),
    "BR-005.md": (
        "---\nid: BR-005\ntitle: renumbered to BR-006\nstatus: void\nfound: 2026-01-06\n"
        "related:\n---\n\nvoid\n"
    ),
}

# Captured by rendering `BUG_FIXTURE` with the engine as it was before it took a register.
BUG_INDEX = (
    "# Bug reports\n\n"
    "_Generated by `stayfixed bugs index` from `bugs/BR-*.md`; edit the entry\n"
    "files, not this one. How to file, close and reference an entry:\n"
    "[runbook](runbooks/bug-reports.md). Audit provenance: [docs/bugs/audits/](bugs/audits/)._\n"
    "\n## Open (1)\n\n"
    "| ID | Sev | Area | Title | Found |\n|---|---|---|---|---|\n"
    "| [BR-001](bugs/BR-001.md) | high | ledger | a pipe \\| and a backslash \\\\ in a title "
    "| 2026-01-02 |\n"
    "\n## Partially fixed (1)\n\n"
    "| ID | Sev | Area | Title | Found |\n|---|---|---|---|---|\n"
    "| [BR-002](bugs/BR-002.md) | medium | hooks | half done | 2026-01-03 |\n"
    "\n## Rejected (1)\n\n"
    "| ID | Sev | Area | Title | Found |\n|---|---|---|---|---|\n"
    "| [BR-003](bugs/BR-003.md) | low | docs | not a bug | 2026-01-04 |\n"
    "\n## Fixed (1)\n\n"
    "| ID | Title | Fixed in |\n|---|---|---|\n"
    "| [BR-004](bugs/BR-004.md) | repaired | `abc1234` |\n"
    "\n## Void identifiers (1)\n\n"
    "| ID | Why |\n|---|---|\n"
    "| [BR-005](bugs/BR-005.md) | renumbered to BR-006 |\n"
)

# The sha256 of the empty index `init` wrote before the engine took a register, which is the
# `bug-index` artifact's digest in every project's `.stayfixed/manifest.json`.
EMPTY_INDEX_SHA256 = "cc18e44ac181a9b61006c00c4f24b0c34e8b769a504513e574a43bbbcad44bcf"

DEBT_TEMPLATE = """---
id: {identifier}
title: {title}
status: open
{size}
{area}
found: {today}
{impact}
{related}
---

What this costs, and what paying it down would take.
"""

DEBT_LIVE = (
    ("ID", "id"),
    ("Size", "size"),
    ("Area", "area"),
    ("Title", "title"),
    ("Impact", "impact"),
)

# A register only this file knows: its own name, title, prefix, levels and a key the bug ledger
# does not have, and no runbook.
DEBT = Register(
    name="debt",
    title="Tech debt",
    directory="docs/debt",
    index="docs/tech-debt.md",
    ids=Identifiers("TD"),
    schema=Schema(
        keys=("id", "title", "status", "size", "area", "found", "impact", "related"),
        required=("id", "title", "status", "found"),
        required_unless_void=("size", "area"),
        statuses=("open", "paid", "void"),
        level="size",
        levels=("XS", "S", "M", "L", "XL"),
        evidence_boundary_for=(),
        template=DEBT_TEMPLATE,
        sections=(
            Section("Open", ("open",), DEBT_LIVE),
            Section("Paid down", ("paid",), (("ID", "id"), ("Title", "title"))),
            Section("Void identifiers", ("void",), (("ID", "id"), ("Why", "title"))),
        ),
    ),
    runbook=None,
)

BUG_LITERALS = ("BR-", "Bug reports", "bug-reports.md", "stayfixed bugs")
# The debt register's commands, which this CLI does not register: spelled through this name so
# that `tests/test_documents.py`, which refuses a command the parser lacks wherever a tracked file
# names one, reads none here.
DEBT_GROUP = "stayfixed debt"


def project(tmp_path: Path) -> Path:
    root = tmp_path / "widget"
    root.mkdir()
    (root / "stayfixed.toml").write_text(CONFIG, encoding="utf-8")
    return root


def file_debt(root: Path, related: tuple[str, ...] = (), **values: str) -> write.Filed:
    return file_entry(
        root,
        DEBT,
        title="the scan walks the tree twice",
        values={"size": "M", "area": "ledger", "impact": "every check pays it", **values},
        related=related,
        today="2026-10-04",
        fetch=False,
    )


def test_the_bug_register_renders_the_index_byte_for_byte(tmp_path: Path) -> None:
    # Mutation (oracle): one heading of the bug ledger's sections changed -> the literal no
    # longer matches. Any byte the bug ledger's index loses to the register is an index every
    # project's `bugs index --check` reports stale.
    root = project(tmp_path)
    (root / "docs" / "bugs").mkdir(parents=True)
    for name, text in BUG_FIXTURE.items():
        (root / "docs" / "bugs" / name).write_text(text, encoding="utf-8")
    register = bug_register(load(root, machine=tmp_path / "m.toml"))
    assert render_index(load_entries(root, register), register) == BUG_INDEX


def test_init_renders_the_empty_index_with_the_same_digest() -> None:
    # Through `init`'s own artifact rather than `render_index([], …)`, so the digest pinned is the
    # one a manifest records. No mutation entry: every byte of the empty index is also a byte of
    # `BUG_INDEX` above, whose test carries the entry; this one adds the path `init` takes.
    prepared = project_templates(
        preset_defaults("widget"),
        resolution=Resolution(None, True),
        document='[stayfixed]\nversion = "0.1.0"\n\n[project]\nname = "widget"\n',
        adopted=False,
    )
    (index,) = [t for t in prepared.footprint if t.id == "bug-index"]
    assert hashlib.sha256(index.render().encode("utf-8")).hexdigest() == EMPTY_INDEX_SHA256


def test_a_second_register_renders_its_own_title_prefix_and_fields(tmp_path: Path) -> None:
    # Mutation (oracle): `new` writes the bug ledger's template whatever the register -> that
    # template names keys the debt register does not have (`severity` first), and the filing
    # fails before anything reaches disk.
    root = project(tmp_path)
    filed = file_debt(root)
    assert filed.identifier == "TD-001"
    assert filed.path == root / "docs" / "debt" / "TD-001.md"
    assert filed.path.read_text(encoding="utf-8") == (
        "---\nid: TD-001\ntitle: the scan walks the tree twice\nstatus: open\nsize: M\n"
        "area: ledger\nfound: 2026-10-04\nimpact: every check pays it\nrelated:\n---\n\n"
        "What this costs, and what paying it down would take.\n"
    )
    (entry,) = load_entries(root, DEBT)
    assert dict(entry.fields) == {
        "size": "M",
        "found": "2026-10-04",
        "impact": "every check pays it",
    }
    assert (root / "docs" / "tech-debt.md").read_text(encoding="utf-8") == (
        "# Tech debt\n\n"
        f"_Generated by `{DEBT_GROUP} index` from `debt/TD-*.md`; edit the entry\n"
        "files, not this one._\n"
        "\n## Open (1)\n\n"
        "| ID | Size | Area | Title | Impact |\n|---|---|---|---|---|\n"
        "| [TD-001](debt/TD-001.md) | M | ledger | the scan walks the tree twice "
        "| every check pays it |\n"
        "\n## Paid down (0)\n\n"
        "| ID | Title |\n|---|---|\n"
        "\n## Void identifiers (0)\n\n"
        "| ID | Why |\n|---|---|\n"
    )


def test_no_bug_literal_reaches_a_second_registers_output(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # Mutation (oracle): the index heads every register "Bug reports" -> the debt index carries
    # it. The refusals are collected from each path that names its register: the level, a related
    # identifier, an allocated file already present, foreign index content, and vanished entries.
    root = project(tmp_path)
    filed = file_debt(root)
    index = root / "docs" / "tech-debt.md"
    outputs = [filed.path.read_text(encoding="utf-8"), index.read_text(encoding="utf-8")]

    def refusal(related: tuple[str, ...] = (), **values: str) -> str:
        with pytest.raises(StayfixedError) as caught:
            file_debt(root, related, **values)
        return str(caught.value)

    outputs.append(refusal(size="huge"))
    outputs.append(refusal(("TD-2",)))

    monkeypatch.setattr(write, "next_identifier", lambda *_, **__: Allocation("TD-001", None))
    outputs.append(refusal())
    monkeypatch.undo()

    clean = index.read_text(encoding="utf-8")
    index.write_text(clean + "\nkept by hand\n", encoding="utf-8")
    outputs.append(refusal())
    index.write_text(clean, encoding="utf-8")

    filed.path.unlink()
    (root / "docs" / "debt").rmdir()
    outputs.append(refusal())

    assert len(outputs) == 7
    assert f"`{DEBT_GROUP} check`" in outputs[4], outputs[4]
    for output in outputs:
        for literal in BUG_LITERALS:
            assert literal not in output, (literal, output)
