"""The ledger engine serves any register, and the bug ledger is one value of it, byte for byte.

The two literals below were captured from the engine before it took a register, and are not
derived from the code under test: every project's manifest records the empty index's digest, so
a change to those bytes is an upgrade every project sees, not a refactor.

stayfixed:ledger:fixtures — the identifiers below are sample data, not claims about a ledger.
"""

from __future__ import annotations

import hashlib
import re
import shutil
from dataclasses import replace
from pathlib import Path
from typing import Any

import pytest

from stayfixed.config.loader import load, preset_defaults
from stayfixed.config.schema import Config
from stayfixed.errors import Failure, StayfixedError
from stayfixed.findings import Finding
from stayfixed.identifiers import Identifiers
from stayfixed.ledger import write
from stayfixed.ledger.check import bugs_gate, register_gate, uninitialised
from stayfixed.ledger.entries import LedgerError, load_entries, parse_entry
from stayfixed.ledger.index import header, render_index
from stayfixed.ledger.register import EVIDENCE_LABEL, Register, Schema, Section, bug_register
from stayfixed.ledger.write import Allocation, file_entry, renumber
from stayfixed.project.api import project_templates
from stayfixed.release.api import Resolution
from tests.gitfixture import git, needs_git

CONFIG = """
[stayfixed]
version = "0.1.0"
state = "installed"
preset = "recommended"
profile = ""
agents = ["claude"]

[project]
name = "widget"
base_branch = "main"
release_branch = "main"
"""

# One entry per status, with a title that exercises the cell escaper and a fixed-in value that
# needs quoting, so the capture below pins every column layout and both escapes.
BUG_FIXTURE = {
    "BR-001.md": (
        '---\nid: BR-001\ntitle: "a pipe | and a backslash \\\\ in a title"\nstatus: open\n'
        "severity: high\narea: ledger\nfound: 2026-01-02\nsource:\nfixed_in:\nrelated: [BR-004]\n"
        "---\n\nbody\n"
    ),
    "BR-002.md": (
        "---\nid: BR-002\ntitle: half done\nstatus: partial\nseverity: medium\narea: hooks\n"
        "found: 2026-01-03\nsource: a review\nfixed_in:\nrelated:\n---\n\nbody\n"
    ),
    "BR-003.md": (
        "---\nid: BR-003\ntitle: not a bug\nstatus: rejected\nseverity: low\narea: docs\n"
        "found: 2026-01-04\nsource:\nfixed_in:\nrelated:\n---\n\nbody\n"
    ),
    "BR-004.md": (
        "---\nid: BR-004\ntitle: repaired\nstatus: fixed\nseverity: high\narea: ledger\n"
        'found: 2026-01-05\nsource:\nfixed_in: "`abc1234`"\nrelated: [BR-001]\n---\n\nbody\n'
    ),
    "BR-005.md": (
        "---\nid: BR-005\ntitle: renumbered to BR-006\nstatus: void\nfound: 2026-01-06\n"
        "related:\n---\n\nvoid\n"
    ),
}

# Captured by rendering `BUG_FIXTURE` with the engine as it was before it took a register.
BUG_INDEX = (
    "# Bug reports\n\n"
    "_Generated by `stayfixed bugs index` from `bugs/BR-*.md`; edit the entry\n"
    "files, not this one. How to file, close and reference an entry:\n"
    "[runbook](runbooks/bug-reports.md). Audit provenance: [docs/bugs/audits/](bugs/audits/)._\n"
    "\n## Open (1)\n\n"
    "| ID | Sev | Area | Title | Found |\n|---|---|---|---|---|\n"
    "| [BR-001](bugs/BR-001.md) | high | ledger | a pipe \\| and a backslash \\\\ in a title "
    "| 2026-01-02 |\n"
    "\n## Partially fixed (1)\n\n"
    "| ID | Sev | Area | Title | Found |\n|---|---|---|---|---|\n"
    "| [BR-002](bugs/BR-002.md) | medium | hooks | half done | 2026-01-03 |\n"
    "\n## Rejected (1)\n\n"
    "| ID | Sev | Area | Title | Found |\n|---|---|---|---|---|\n"
    "| [BR-003](bugs/BR-003.md) | low | docs | not a bug | 2026-01-04 |\n"
    "\n## Fixed (1)\n\n"
    "| ID | Title | Fixed in |\n|---|---|---|\n"
    "| [BR-004](bugs/BR-004.md) | repaired | `abc1234` |\n"
    "\n## Void identifiers (1)\n\n"
    "| ID | Why |\n|---|---|\n"
    "| [BR-005](bugs/BR-005.md) | renumbered to BR-006 |\n"
)

# The sha256 of the empty index `init` wrote before the engine took a register, which is the
# `bug-index` artifact's digest in every project's `.stayfixed/manifest.json`.
EMPTY_INDEX_SHA256 = "cc18e44ac181a9b61006c00c4f24b0c34e8b769a504513e574a43bbbcad44bcf"

DEBT_TEMPLATE = """---
id: {identifier}
title: {title}
status: open
{size}
{area}
found: {today}
{impact}
{related}
---

What this costs, and what paying it down would take.
"""

DEBT_LIVE = (
    ("ID", "id"),
    ("Size", "size"),
    ("Area", "area"),
    ("Title", "title"),
    ("Impact", "impact"),
)

# A register only this file knows: its own name, title, prefix, levels and a key the bug ledger
# does not have, and neither a runbook nor an audits directory.
DEBT = Register(
    name="debt",
    title="Tech debt",
    directory="docs/debt",
    index="docs/tech-debt.md",
    ids=Identifiers("TD"),
    schema=Schema(
        keys=("id", "title", "status", "size", "area", "found", "impact", "related"),
        required=("id", "title", "status", "found"),
        required_unless_void=("size", "area"),
        statuses=("open", "paid", "void"),
        void="void",
        level="size",
        levels=("XS", "S", "M", "L", "XL"),
        evidence_boundary_for=(),
        dates=("found",),
        template=DEBT_TEMPLATE,
        sections=(
            Section("Open", ("open",), DEBT_LIVE),
            Section("Paid down", ("paid",), (("ID", "id"), ("Title", "title"))),
            Section("Void identifiers", ("void",), (("ID", "id"), ("Why", "title"))),
        ),
    ),
    runbook=None,
    audits=None,
)

BUG_LITERALS = ("BR-", "Bug reports", "bug-reports.md", "stayfixed bugs")
# The debt register's commands, which this CLI does not register: spelled through this name so
# that `tests/test_documents.py`, which refuses a command the parser lacks wherever a tracked file
# names one, reads none here.
DEBT_GROUP = "stayfixed debt"


def project(tmp_path: Path) -> Path:
    root = tmp_path / "widget"
    root.mkdir()
    (root / "stayfixed.toml").write_text(CONFIG, encoding="utf-8")
    return root


def file_debt(root: Path, related: tuple[str, ...] = (), **values: str) -> write.Filed:
    return file_entry(
        root,
        DEBT,
        title="the scan walks the tree twice",
        values={"size": "M", "area": "ledger", "impact": "every check pays it", **values},
        related=related,
        today="2026-10-04",
        fetch=False,
    )


def test_the_bug_register_renders_the_index_byte_for_byte(tmp_path: Path) -> None:
    # Mutation (oracle): one heading of the bug ledger's sections changed -> the literal no
    # longer matches. Any byte the bug ledger's index loses to the register is an index every
    # project's `bugs index --check` reports stale.
    root = project(tmp_path)
    (root / "docs" / "bugs").mkdir(parents=True)
    for name, text in BUG_FIXTURE.items():
        (root / "docs" / "bugs" / name).write_text(text, encoding="utf-8")
    register = bug_register(load(root, machine=tmp_path / "m.toml"))
    assert render_index(load_entries(root, register), register) == BUG_INDEX


def test_init_renders_the_empty_index_with_the_same_digest() -> None:
    # Through `init`'s own artifact rather than `render_index([], …)`, so the digest pinned is the
    # one a manifest records. No mutation entry: every byte of the empty index is also a byte of
    # `BUG_INDEX` above, whose test carries the entry; this one adds the path `init` takes.
    prepared = project_templates(
        preset_defaults("widget"),
        resolution=Resolution(None, True),
        document='[stayfixed]\nversion = "0.1.0"\n\n[project]\nname = "widget"\n',
        adopted=False,
    )
    (index,) = [t for t in prepared.footprint if t.id == "bug-index"]
    assert hashlib.sha256(index.render().encode("utf-8")).hexdigest() == EMPTY_INDEX_SHA256


def test_a_second_register_renders_its_own_title_prefix_and_fields(tmp_path: Path) -> None:
    # Mutation (oracle): `new` writes the bug ledger's template whatever the register -> that
    # template names keys the debt register does not have (`severity` first), and the filing
    # fails before anything reaches disk.
    root = project(tmp_path)
    filed = file_debt(root)
    assert filed.identifier == "TD-001"
    assert filed.path == root / "docs" / "debt" / "TD-001.md"
    assert filed.path.read_text(encoding="utf-8") == (
        "---\nid: TD-001\ntitle: the scan walks the tree twice\nstatus: open\nsize: M\n"
        "area: ledger\nfound: 2026-10-04\nimpact: every check pays it\nrelated:\n---\n\n"
        "What this costs, and what paying it down would take.\n"
    )
    (entry,) = load_entries(root, DEBT)
    assert dict(entry.fields) == {
        "size": "M",
        "found": "2026-10-04",
        "impact": "every check pays it",
    }
    assert (root / "docs" / "tech-debt.md").read_text(encoding="utf-8") == (
        "# Tech debt\n\n"
        f"_Generated by `{DEBT_GROUP} index` from `debt/TD-*.md`; edit the entry\n"
        "files, not this one._\n"
        "\n## Open (1)\n\n"
        "| ID | Size | Area | Title | Impact |\n|---|---|---|---|---|\n"
        "| [TD-001](debt/TD-001.md) | M | ledger | the scan walks the tree twice "
        "| every check pays it |\n"
        "\n## Paid down (0)\n\n"
        "| ID | Title |\n|---|---|\n"
        "\n## Void identifiers (0)\n\n"
        "| ID | Why |\n|---|---|\n"
    )


def test_no_bug_literal_reaches_a_second_registers_output(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # Mutation (oracle): the index heads every register "Bug reports" -> the debt index carries
    # it. The refusals are collected from each path that names its register: the level, a related
    # identifier, an allocated file already present, foreign index content, and vanished entries.
    root = project(tmp_path)
    filed = file_debt(root)
    index = root / "docs" / "tech-debt.md"
    outputs = [filed.path.read_text(encoding="utf-8"), index.read_text(encoding="utf-8")]

    def refusal(related: tuple[str, ...] = (), **values: str) -> str:
        with pytest.raises(StayfixedError) as caught:
            file_debt(root, related, **values)
        return str(caught.value)

    outputs.append(refusal(size="huge"))
    outputs.append(refusal(("TD-2",)))

    monkeypatch.setattr(write, "next_identifier", lambda *_, **__: Allocation("TD-001", None))
    outputs.append(refusal())
    monkeypatch.undo()

    clean = index.read_text(encoding="utf-8")
    index.write_text(clean + "\nkept by hand\n", encoding="utf-8")
    outputs.append(refusal())
    index.write_text(clean, encoding="utf-8")

    filed.path.unlink()
    (root / "docs" / "debt").rmdir()
    outputs.append(refusal())

    assert len(outputs) == 7
    assert f"`{DEBT_GROUP} check`" in outputs[4], outputs[4]
    for output in outputs:
        for literal in BUG_LITERALS:
            assert literal not in output, (literal, output)


@pytest.mark.parametrize(
    ("declared", "tail"),
    [
        pytest.param(
            {"runbook": "docs/guides/debt.md"},
            " How to file, close and reference an entry:\n[runbook](guides/debt.md)._\n",
            id="a-runbook-and-no-audits",
        ),
        pytest.param(
            {"audits": "audits"},
            " Audit provenance: [docs/debt/audits/](debt/audits/)._\n",
            id="audits-and-no-runbook",
        ),
    ],
)
def test_the_index_links_only_the_runbook_and_audits_its_register_declares(
    declared: dict[str, Any], tail: str
) -> None:
    # The audits directory is one `init` writes beside the bug ledger alone, so a register with a
    # runbook must not be handed a link to an audits directory nobody created. Mutation (oracle):
    # the audits sentence asks whether there is a runbook -> the first case renders `None/`.
    assert header(replace(DEBT, **declared)) == (
        "# Tech debt\n\n"
        f"_Generated by `{DEBT_GROUP} index` from `debt/TD-*.md`; edit the entry\n"
        "files, not this one." + tail
    )


def withdrawn_register() -> Register:
    """The debt register with its date key and its void status under names the bug ledger does not
    use, so a rule the engine keyed on `found` or `void` passes it by."""
    return replace(
        DEBT,
        schema=replace(
            DEBT.schema,
            keys=("id", "title", "status", "size", "area", "noted", "impact", "related"),
            required=("id", "title", "status", "noted"),
            statuses=("open", "paid", "withdrawn"),
            dates=("noted",),
            void="withdrawn",
            template=DEBT_TEMPLATE.replace("found: {today}", "noted: {today}"),
            sections=(
                *DEBT.schema.sections[:2],
                Section("Withdrawn", ("withdrawn",), (("ID", "id"), ("Why", "title"))),
            ),
        ),
    )


def test_a_second_register_names_its_own_date_key_and_void_status() -> None:
    # Mutations (oracle): the void status read as the literal `void` -> the withdrawn entry is
    # refused for its missing `size`; the date keys read as `found` alone -> `noted: soon` parses;
    # the date refusal names `found` whatever the key -> the messages below differ.
    register = withdrawn_register()
    path = Path("docs/debt/TD-001.md")

    def entry(status: str, noted: str) -> str:
        return f"---\nid: TD-001\ntitle: filed twice\nstatus: {status}\nnoted: {noted}\n---\n\n"

    withdrawn = parse_entry(entry("withdrawn", "2026-10-04"), path=path, register=register)
    assert (withdrawn.status, withdrawn.fields["size"], withdrawn.area) == ("withdrawn", "", "")

    def refusal(noted: str) -> str:
        text = entry("paid", noted).replace("status: paid", "status: paid\nsize: S\narea: a")
        with pytest.raises(LedgerError) as caught:
            parse_entry(text, path=path, register=register)
        return str(caught.value)

    assert refusal("soon") == (
        "docs/debt/TD-001.md: `noted` must be an ISO date (YYYY-MM-DD), got 'soon'"
    )
    assert refusal("2026-02-30") == (
        "docs/debt/TD-001.md: `noted` names a date that does not exist: '2026-02-30'"
    )


# Captured from the reader before the engine took a register (`found` as each case gives it).
BUG_DATE_REFUSALS = {
    "soon": "docs/bugs/BR-001.md: `found` must be an ISO date (YYYY-MM-DD), got 'soon'",
    "2026-02-30": "docs/bugs/BR-001.md: `found` names a date that does not exist: '2026-02-30'",
    "20260102": "docs/bugs/BR-001.md: `found` must be an ISO date (YYYY-MM-DD), got '20260102'",
    '""': "docs/bugs/BR-001.md: `found` must be an ISO date (YYYY-MM-DD), got ''",
}


@pytest.mark.parametrize("found", list(BUG_DATE_REFUSALS))
def test_the_bug_ledgers_date_refusals_keep_their_words(tmp_path: Path, found: str) -> None:
    # Mutation (oracle): the date refusal reworded -> each case differs from its capture.
    register = bug_register(load(project(tmp_path), machine=tmp_path / "m.toml"))
    text = (
        "---\nid: BR-001\ntitle: t\nstatus: open\nseverity: high\narea: a\n"
        f"found: {found}\n---\n\nbody\n"
    )
    with pytest.raises(LedgerError) as caught:
        parse_entry(text, path=Path("docs/bugs/BR-001.md"), register=register)
    assert str(caught.value) == BUG_DATE_REFUSALS[found]


@pytest.mark.parametrize(
    ("changes", "problem"),
    [
        pytest.param(
            {"required": ("id", "status", "found")},
            "`title` is read from every entry, so it must be required",
            id="title-not-required",
        ),
        pytest.param(
            {"required": ("id", "title", "status", "due")},
            "required names `due`, which is not a key",
            id="required-not-a-key",
        ),
        pytest.param(
            {"required_unless_void": ("size", "owner")},
            "required_unless_void names `owner`, which is not a key",
            id="required-unless-void-not-a-key",
        ),
        pytest.param(
            {"dates": ("found", "due")},
            "dates names `due`, which is not a key",
            id="date-not-a-key",
        ),
        pytest.param({"level": "weight"}, "level `weight` is not a key", id="level-not-a-key"),
        pytest.param({"void": "dropped"}, "void `dropped` is not a status", id="void-not-a-status"),
        pytest.param(
            {"statuses": ("open", "paid", "void", "parked")},
            "status `parked` is gathered by 0 sections, not one",
            id="status-in-no-section",
        ),
        pytest.param(
            {"sections": (*DEBT.schema.sections, Section("Again", ("open",), DEBT_LIVE))},
            "status `open` is gathered by 2 sections, not one",
            id="status-in-two-sections",
        ),
        pytest.param(
            {"sections": (*DEBT.schema.sections, Section("Parked", ("parked",), DEBT_LIVE))},
            "section `Parked` gathers `parked`, which is not a status",
            id="section-status-not-a-status",
        ),
        pytest.param(
            {
                "sections": (
                    Section("Open", ("open",), (("Due", "due"),)),
                    *DEBT.schema.sections[1:],
                )
            },
            "section `Open` shows `due`, which is not a key a cell can show",
            id="column-not-a-key",
        ),
        pytest.param(
            {
                "sections": (
                    Section("Open", ("open",), (("See", "related"),)),
                    *DEBT.schema.sections[1:],
                )
            },
            "section `Open` shows `related`, which is not a key a cell can show",
            id="column-is-related",
        ),
        pytest.param(
            {"template": DEBT_TEMPLATE + "{owner}\n"},
            "the template's `{owner}` is not a line of a key the writer is handed",
            id="template-placeholder-not-a-key",
        ),
        pytest.param(
            {"template": DEBT_TEMPLATE.replace("status: open", "{status}")},
            "the template's `{status}` is not a line of a key the writer is handed",
            id="template-placeholder-the-writer-owns",
        ),
        pytest.param(
            {"required": ("id", "title", "status", "found", "impact")},
            "required `impact` is not a date, so `renumber`'s void entry cannot fill it",
            id="required-not-a-date",
        ),
        pytest.param(
            {
                "keys": tuple(key for key in DEBT.schema.keys if key != "related"),
                "template": DEBT_TEMPLATE.replace("{related}\n", ""),
            },
            "`related` is not a key, so `renumber`'s void entry cannot name the new number",
            id="no-related-key",
        ),
        pytest.param(
            {"keys": (*DEBT.schema.keys, "area")},
            "key `area` is listed more than once",
            id="key-listed-twice",
        ),
        pytest.param(
            {"template": DEBT_TEMPLATE.replace("status: open", "status: draft")},
            "the template writes status `draft`, which is not a status",
            id="template-status-not-a-status",
        ),
        pytest.param(
            {"template": DEBT_TEMPLATE.replace("status: open\n", "")},
            "the template has no `status:` line, so an entry it writes has no status",
            id="template-without-status",
        ),
        pytest.param(
            {"template": DEBT_TEMPLATE.replace("{identifier}", "TD-000")},
            "the template has no `{identifier}`, so an entry it writes carries no number",
            id="template-without-identifier",
        ),
        pytest.param(
            {"level": "title"},
            "level `title` has no line of its own in the template, so `new` cannot write it",
            id="level-without-a-line",
        ),
        pytest.param(
            {"required_unless_void": ("size", "area", "found")},
            "required_unless_void `found` has no line of its own in the template, so `new` "
            "cannot write it",
            id="required-unless-void-without-a-line",
        ),
        pytest.param(
            {"required_unless_void": ("area",)},
            "level `size` is neither required nor required_unless_void",
            id="level-not-required",
        ),
    ],
)
def test_a_schema_built_wrong_is_refused_at_construction(
    changes: dict[str, Any], problem: str
) -> None:
    # Each of these was a `KeyError` (or a status silently missing from the index) on the first
    # entry that reached it, far from the register that was built wrong. Mutations (oracle): one
    # per rule, each dropping its check -> its case constructs.
    with pytest.raises(ValueError, match=re.escape(problem)):
        replace(DEBT.schema, **changes)


# The bug ledger's header and an entry's row on each `[paths]` layout the loader accepts, captured
# from the engine before it took a register: the links are relative to the index's own directory,
# so a layout where the ledger directory is that directory renders it as `./`, and one where the
# index sits deeper or at the root renders `../` or the whole path. Every byte here is a byte of an
# index some project has committed, which `bugs index --check` compares against.
LAYOUT_CAPTURES = [
    pytest.param(
        "",
        (
            "# Bug reports\n"
            "\n"
            "_Generated by `stayfixed bugs index` from `bugs/BR-*.md`; edit the entry\n"
            "files, not this one. How to file, close and reference an entry:\n"
            "[runbook](runbooks/bug-reports.md). "
            "Audit provenance: [docs/bugs/audits/](bugs/audits/)._\n"
        ),
        "| [BR-001](bugs/BR-001.md) | high | a | t | 2026-01-02 |",
        id="default",
    ),
    pytest.param(
        '\n[paths]\nbugs = "docs"\nbug_index = "docs/bug-reports.md"\n',
        (
            "# Bug reports\n"
            "\n"
            "_Generated by `stayfixed bugs index` from `./BR-*.md`; edit the entry\n"
            "files, not this one. How to file, close and reference an entry:\n"
            "[runbook](runbooks/bug-reports.md). "
            "Audit provenance: [docs/audits/](./audits/)._\n"
        ),
        "| [BR-001](./BR-001.md) | high | a | t | 2026-01-02 |",
        id="bugs-is-index-dir-docs",
    ),
    pytest.param(
        '\n[paths]\nbugs = "bugs"\nbug_index = "bugs/README.md"\nrunbooks = "guides"\n',
        (
            "# Bug reports\n"
            "\n"
            "_Generated by `stayfixed bugs index` from `./BR-*.md`; edit the entry\n"
            "files, not this one. How to file, close and reference an entry:\n"
            "[runbook](../guides/bug-reports.md). "
            "Audit provenance: [bugs/audits/](./audits/)._\n"
        ),
        "| [BR-001](./BR-001.md) | high | a | t | 2026-01-02 |",
        id="bugs-is-index-dir-readme",
    ),
    pytest.param(
        '\n[paths]\nbug_index = "BUGS.md"\nrunbooks = "guides"\n',
        (
            "# Bug reports\n"
            "\n"
            "_Generated by `stayfixed bugs index` from `docs/bugs/BR-*.md`; edit the entry\n"
            "files, not this one. How to file, close and reference an entry:\n"
            "[runbook](guides/bug-reports.md). "
            "Audit provenance: [docs/bugs/audits/](docs/bugs/audits/)._\n"
        ),
        "| [BR-001](docs/bugs/BR-001.md) | high | a | t | 2026-01-02 |",
        id="index-at-root",
    ),
    pytest.param(
        '\n[paths]\nbugs = "bugs"\nbug_index = "docs/ledger/index.md"\n',
        (
            "# Bug reports\n"
            "\n"
            "_Generated by `stayfixed bugs index` from `../../bugs/BR-*.md`; edit the entry\n"
            "files, not this one. How to file, close and reference an entry:\n"
            "[runbook](../runbooks/bug-reports.md). "
            "Audit provenance: [bugs/audits/](../../bugs/audits/)._\n"
        ),
        "| [BR-001](../../bugs/BR-001.md) | high | a | t | 2026-01-02 |",
        id="index-deeper",
    ),
    pytest.param(
        '\n[paths]\nrunbooks = "docs"\n',
        (
            "# Bug reports\n"
            "\n"
            "_Generated by `stayfixed bugs index` from `bugs/BR-*.md`; edit the entry\n"
            "files, not this one. How to file, close and reference an entry:\n"
            "[runbook](bug-reports.md). "
            "Audit provenance: [docs/bugs/audits/](bugs/audits/)._\n"
        ),
        "| [BR-001](bugs/BR-001.md) | high | a | t | 2026-01-02 |",
        id="runbooks-at-index-dir",
    ),
    pytest.param(
        '\n[paths]\nbugs = "ledger/entries"\nbug_index = "ledger/INDEX.md"\nrunbooks = "guides"\n',
        (
            "# Bug reports\n"
            "\n"
            "_Generated by `stayfixed bugs index` from `entries/BR-*.md`; edit the entry\n"
            "files, not this one. How to file, close and reference an entry:\n"
            "[runbook](../guides/bug-reports.md). "
            "Audit provenance: [ledger/entries/audits/](entries/audits/)._\n"
        ),
        "| [BR-001](entries/BR-001.md) | high | a | t | 2026-01-02 |",
        id="nested-elsewhere",
    ),
]


@pytest.mark.parametrize(("paths", "expected_header", "expected_row"), LAYOUT_CAPTURES)
def test_the_bug_ledgers_header_and_links_keep_their_bytes_on_every_layout(
    tmp_path: Path, paths: str, expected_header: str, expected_row: str
) -> None:
    # Mutation (oracle): the audits link rendered as the relative path to `<directory>/audits`
    # rather than appended to the directory's own link -> the two layouts whose ledger directory is
    # the index's directory lose their `./`.
    root = tmp_path / "widget"
    root.mkdir()
    (root / "stayfixed.toml").write_text(CONFIG + paths, encoding="utf-8")
    register = bug_register(load(root, machine=tmp_path / "m.toml"))
    directory = root / register.directory
    directory.mkdir(parents=True, exist_ok=True)
    (directory / "BR-001.md").write_text(
        "---\nid: BR-001\ntitle: t\nstatus: open\nseverity: high\narea: a\n"
        "found: 2026-01-02\nsource:\nfixed_in:\nrelated:\n---\n\nbody\n",
        encoding="utf-8",
    )
    rendered = render_index(load_entries(root, register), register)
    assert header(register) == expected_header
    assert rendered.startswith(expected_header)
    assert expected_row in rendered.splitlines()


def regenerate(root: Path, register: Register) -> None:
    """Write the register's index from its entry files, as `index` would."""
    (root / register.index).write_text(
        render_index(load_entries(root, register), register), encoding="utf-8"
    )


def committed_debt(tmp_path: Path) -> tuple[Path, Config, str]:
    """A project whose one commit carries the debt register's `TD-001` and `TD-002` and their
    index, and no bug ledger; the commit's id is the base, and the tree is left as committed."""
    root = project(tmp_path)
    file_debt(root)
    file_debt(root)
    git(root, "init", "-q", "-b", "main")
    git(root, "add", "-A")
    git(root, "commit", "-q", "-m", "base")
    return root, load(root, machine=tmp_path / "m.toml"), git(root, "rev-parse", "HEAD").strip()


def test_a_second_register_without_its_directory_is_inert_while_the_bug_ledger_is_live(
    tmp_path: Path,
) -> None:
    # A second register a project has not started yet must not read the bug ledger's live tree
    # as its own. Mutation (oracle): `uninitialised` reads the bug ledger's directory whatever
    # the register -> the debt register finds `docs/bugs/` there and is judged as a ledger whose
    # own directory went missing.
    root = project(tmp_path)
    config = load(root, machine=tmp_path / "m.toml")
    bugs = bug_register(config)
    (root / "docs" / "bugs").mkdir(parents=True)
    for name, text in BUG_FIXTURE.items():
        (root / "docs" / "bugs" / name).write_text(text, encoding="utf-8")
    assert not (root / "docs" / "debt").exists() and not (root / "docs" / "tech-debt.md").exists()
    assert (uninitialised(root, DEBT), uninitialised(root, bugs)) == (True, False)
    assert register_gate(root, config, DEBT) == []
    # The bug ledger's gate runs: its two `high` entries never filled the evidence line, and its
    # index was never written.
    assert [(f.rule, f.path) for f in register_gate(root, config, bugs)] == [
        ("evidence-boundary", "docs/bugs/BR-001.md"),
        ("evidence-boundary", "docs/bugs/BR-004.md"),
        ("stale-index", "docs/bug-reports.md"),
    ]


@needs_git
def test_the_gate_judges_a_second_register_against_its_base(tmp_path: Path) -> None:
    # Mutation (oracle): the base's entries are read with the bug ledger's identifiers ->
    # `TD-001.md` is no entry to the base's listing, and its removal passes.
    root, config, base = committed_debt(tmp_path)
    (root / "docs" / "debt" / "TD-001.md").unlink()
    regenerate(root, DEBT)
    assert register_gate(root, config, DEBT, base) == [
        Finding(
            "entry-removed",
            "docs/debt/TD-001.md",
            None,
            "a commit this change forked from the base at carries this entry and this tree does "
            "not; ledger entries are never deleted: restore it from the base, and move one with "
            f"`{DEBT_GROUP} renumber`, which leaves a `void` entry at the old number",
        )
    ]
    # Without a base the tree alone is judged, and it is a consistent ledger of one entry.
    assert register_gate(root, config, DEBT) == []


@needs_git
def test_a_second_registers_findings_name_its_own_paths_and_commands(tmp_path: Path) -> None:
    # Every text the gate renders from a register names that register: its directory, its index,
    # its command group, its identifiers. Mutations (oracle): the stale remedy, the removed-ledger
    # refusal and the unread-base failure each name the bug ledger's group whatever the register
    # -> each text below says `bugs`; the scan reads the bug ledger's identifiers, or its
    # directory's name, for mentions and citations -> neither `TD-404` is found.
    root, config, base = committed_debt(tmp_path)
    directory, index = root / "docs" / "debt", root / "docs" / "tech-debt.md"
    copied = (directory / "TD-002.md").read_text(encoding="utf-8").replace("TD-002", "TD-003")
    (directory / "TD-003.md").write_text(copied, encoding="utf-8")
    (root / "src").mkdir()
    (root / "src" / "a.py").write_text("# workaround for TD-404\n", encoding="utf-8")
    (root / "docs" / "plan.md").write_text("see [x](debt/TD-404.md)\n", encoding="utf-8")
    mention = (
        "dangling-mention",
        "src/a.py",
        "mentions TD-404, which has no entry file (referenced 1 time(s))",
    )
    citation = (
        "dangling-citation",
        "docs/plan.md",
        "cites docs/debt/TD-404.md, which does not exist (referenced 1 time(s))",
    )
    live = register_gate(root, config, DEBT, base)
    assert [(f.rule, f.path, f.detail) for f in live] == [
        ("stale-index", "docs/tech-debt.md", f"is stale; run: {DEBT_GROUP} index"),
        mention,
        citation,
    ]

    with pytest.raises(Failure) as caught:
        register_gate(root, config, DEBT, "refs/heads/nowhere")
    unread = str(caught.value)
    assert unread.replace(str(root), "<root>") == (
        "what the commits HEAD forked from `refs/heads/nowhere` at hold of docs/debt and "
        "docs/tech-debt.md is unknown under <root> (git exited 128), so whether this change "
        "deleted the ledger or an entry of it is unknown and the debt gate proved nothing. Fetch "
        "the whole history (`fetch-depth: 0` in CI), or pass a `--base` this clone holds that "
        "shares history with HEAD"
    )

    shutil.rmtree(directory)
    missing = register_gate(root, config, DEBT, base)
    assert [(f.rule, f.path) for f in missing] == [
        ("entries-missing", "docs/tech-debt.md"),
        ("entry-removed", "docs/debt/TD-001.md"),
        ("entry-removed", "docs/debt/TD-002.md"),
    ]
    assert missing[0].detail == (
        "docs/debt/ does not exist, but docs/tech-debt.md is this tool's generated index; the "
        "entry files are the ledger and the index carries nothing of its own, so restore them "
        "rather than regenerating over it"
    )

    index.unlink()
    removed = register_gate(root, config, DEBT, base)
    assert [(f.rule, f.path, f.detail) for f in removed] == [
        (
            "ledger-removed",
            "docs/debt",
            "a commit this change forked from the base at carries the ledger (docs/debt or "
            "docs/tech-debt.md) and this tree has neither; deleting the ledger does not switch "
            "the debt gate off: restore it from the base",
        ),
        mention,
        citation,
    ]
    for text in [unread, *(f.detail for f in (*live, *missing, *removed))]:
        for literal in (*BUG_LITERALS, "bugs gate"):
            assert literal not in text, (literal, text)


@pytest.mark.parametrize(
    ("size", "body", "rule", "detail"),
    [
        pytest.param(
            "S",
            "- **Size:** S\n",
            "state-in-body",
            "body restates `**Status:**`/`**Size:**`; those live in the frontmatter alone",
            id="state-in-body",
        ),
        pytest.param(
            "L",
            "body\n",
            "evidence-boundary",
            f"size `L` needs a filled `{EVIDENCE_LABEL}` line — a plan built on this entry "
            "inherits its silences as premises",
            id="evidence-boundary",
        ),
    ],
)
def test_a_second_register_holds_its_own_level_to_the_body_rules(
    tmp_path: Path, size: str, body: str, rule: str, detail: str
) -> None:
    # Mutations (oracle): the evidence rule reads `[ledger] evidence_boundary_required_for` rather
    # than the register's own levels -> `L` is not in it and the second case passes; the body rule
    # looks for the bug ledger's `**Severity:**` bullet -> the first case passes.
    root = project(tmp_path)
    config = load(root, machine=tmp_path / "m.toml")
    register = replace(DEBT, schema=replace(DEBT.schema, evidence_boundary_for=("L",)))
    (root / "docs" / "debt").mkdir(parents=True)
    (root / "docs" / "debt" / "TD-001.md").write_text(
        f"---\nid: TD-001\ntitle: t\nstatus: open\nsize: {size}\narea: a\nfound: 2026-10-04\n"
        f"impact:\nrelated:\n---\n\n{body}",
        encoding="utf-8",
    )
    regenerate(root, register)
    found = register_gate(root, config, register)
    assert [(f.rule, f.path, f.detail) for f in found] == [(rule, "docs/debt/TD-001.md", detail)]


# The void entry `renumber` left at the old number, captured from the engine before it took a
# register (`renumber(root, config, "BR-001", "BR-009", today="2026-01-02")` over an entry titled
# `"a: title"`).
BUG_VOID_ENTRY = (
    '---\nid: BR-001\ntitle: "renumbered to BR-009 — a: title"\nstatus: void\n'
    "found: 2026-01-02\nrelated: [BR-009]\n---\n\n"
    "Renumbered to [BR-009](BR-009.md) to resolve an identifier collision. The number stays\n"
    "occupied so a reference written before the repair still lands on an explanation.\n"
)


def test_renumber_leaves_the_bug_ledgers_void_entry_byte_for_byte(tmp_path: Path) -> None:
    # No mutation entry of its own: the second register's case below carries the entry that
    # spells the void entry from the register, and this one holds what that spelling gives the
    # bug ledger to the bytes it always wrote.
    root = project(tmp_path)
    config = load(root, machine=tmp_path / "m.toml")
    (root / "docs" / "bugs").mkdir(parents=True)
    (root / "docs" / "bugs" / "BR-001.md").write_text(
        '---\nid: BR-001\ntitle: "a: title"\nstatus: open\nseverity: low\narea: a\n'
        "found: 2026-01-01\nsource:\nfixed_in:\nrelated:\n---\n\nbody\n",
        encoding="utf-8",
    )
    renumber(root, config, bug_register(config), "BR-001", "BR-009", today="2026-01-02")
    assert (root / "docs" / "bugs" / "BR-001.md").read_text(encoding="utf-8") == BUG_VOID_ENTRY


def test_renumber_leaves_a_second_registers_own_void_entry(tmp_path: Path) -> None:
    # Mutation (oracle): the void entry spells the bug ledger's `void` status and `found` date
    # whatever the register -> the withdrawn register cannot read the entry it was left.
    root = project(tmp_path)
    config = load(root, machine=tmp_path / "m.toml")
    register = withdrawn_register()
    file_entry(
        root,
        register,
        title="filed twice",
        values={"size": "S", "area": "a", "impact": ""},
        related=(),
        today="2026-10-04",
        fetch=False,
    )
    renumber(root, config, register, "TD-001", "TD-009", today="2026-10-05")
    assert (root / "docs" / "debt" / "TD-001.md").read_text(encoding="utf-8") == (
        '---\nid: TD-001\ntitle: "renumbered to TD-009 — filed twice"\nstatus: withdrawn\n'
        "noted: 2026-10-05\nrelated: [TD-009]\n---\n\n"
        "Renumbered to [TD-009](TD-009.md) to resolve an identifier collision. The number stays\n"
        "occupied so a reference written before the repair still lands on an explanation.\n"
    )
    assert [(e.id, e.status) for e in load_entries(root, register)] == [
        ("TD-001", "withdrawn"),
        ("TD-009", "open"),
    ]


def bug_entry(number: int) -> str:
    return (
        f"---\nid: BR-{number:03d}\ntitle: a title\nstatus: open\nseverity: low\n"
        f"area: an area\nfound: 2026-01-01\nsource:\nfixed_in:\nrelated: \n---\n\nbody\n"
    )


# The four texts a change that removes part of the bug ledger, or a stale index, is told, rendered
# by `problems()` before it took a register. `<root>` stands for the checkout.
BUG_REFUSALS = {
    "ledger-removed": [
        (
            "ledger-removed",
            "docs/bugs",
            None,
            "a commit this change forked from the base at carries the ledger (docs/bugs or "
            "docs/bug-reports.md) and this tree has neither; deleting the ledger does not switch "
            "the bugs gate off: restore it from the base",
        )
    ],
    "entry-removed": [
        (
            "entry-removed",
            "docs/bugs/BR-002.md",
            None,
            "a commit this change forked from the base at carries this entry and this tree does "
            "not; ledger entries are never deleted: restore it from the base, and move one with "
            "`stayfixed bugs renumber`, which leaves a `void` entry at the old number",
        )
    ],
    "stale-index": [
        ("stale-index", "docs/bug-reports.md", None, "is stale; run: stayfixed bugs index")
    ],
}
BUG_BASE_UNREAD = (
    "what the commits HEAD forked from `refs/heads/nowhere` at hold of docs/bugs and "
    "docs/bug-reports.md is unknown under <root> (git exited 128), so whether this change "
    "deleted the ledger or an entry of it is unknown and the bugs gate proved nothing. Fetch the "
    "whole history (`fetch-depth: 0` in CI), or pass a `--base` this clone holds that shares "
    "history with HEAD"
)


@needs_git
@pytest.mark.parametrize("case", ["ledger-removed", "entry-removed", "base-unread", "stale-index"])
def test_the_bug_ledgers_refusals_are_unchanged(tmp_path: Path, case: str) -> None:
    # Through `bugs_gate`, the function `bugs check` and the gate run answer with. No mutation
    # entry of its own: the second register's texts carry the entries that make these name the
    # register, and this holds what they give the bug ledger to the bytes it always rendered.
    root = project(tmp_path)
    config = load(root, machine=tmp_path / "m.toml")
    bugs = bug_register(config)
    git(root, "init", "-q", "-b", "main")
    (root / "docs" / "bugs").mkdir(parents=True)
    for number in (1, 2):
        (root / "docs" / "bugs" / f"BR-{number:03d}.md").write_text(
            bug_entry(number), encoding="utf-8"
        )
    regenerate(root, bugs)
    git(root, "add", "-A")
    git(root, "commit", "-q", "-m", "base")
    base = git(root, "rev-parse", "HEAD").strip()
    if case == "base-unread":
        with pytest.raises(Failure) as caught:
            bugs_gate(root, config, "refs/heads/nowhere")
        assert str(caught.value).replace(str(root), "<root>") == BUG_BASE_UNREAD
        return
    if case == "ledger-removed":
        shutil.rmtree(root / "docs" / "bugs")
        (root / "docs" / "bug-reports.md").unlink()
    elif case == "entry-removed":
        (root / "docs" / "bugs" / "BR-002.md").unlink()
        regenerate(root, bugs)
    else:
        (root / "docs" / "bugs" / "BR-003.md").write_text(bug_entry(3), encoding="utf-8")
        base = ""
    found = bugs_gate(root, config, base)
    assert [(f.rule, f.path, f.line, f.detail) for f in found] == BUG_REFUSALS[case]
