"""What planning both passes over the smoke fixture still says.

The fixture is grown rather than generated at smoke time: `stayfixed init --yes --no-ci` ran on a
copy of it once, and the manifest and the footprint it wrote were committed back. So the claims
this module holds are the ones that can go stale — that planning both passes over the fixture
today has nothing left to *create*, that every artifact its manifest records is one the plan
recognises as already correct, that every provenance the manifest records is the one this
build would write for that artifact, and that every digest it records is the one `upgrade` will
recognise as its own when a template changes.

`stayfixed.toml` itself was kept exactly as hand-written rather than let that same `init --yes
--no-ci` run replace it, and deliberately so: a fixture built fresh at smoke time would need a
`[ci] ref` pin that does not exist yet, and would make the smoke suite depend on `init` finishing
cleanly rather than on a tree already known to satisfy every gate. The manifest carries no
`config` record for it, and that absence is not an edit — `stayfixed.toml` is a create-once
artifact, this one already existed on the copy that run acted on, and the run reported it
`skip_modified` and recorded nothing for it, the same as the other write-once artifacts above.
The `state = "installed"` it declares is the fixture's own and is what makes the gates this
project runs over it enforce instead of merely warn; `init` itself writes `initialised`.

**It is not "the fixture is what the shipped templates render", which is what this module's first
line used to say.** Measured on a copy: seven footprint artifacts come back `unchanged`, the
three write-once ones come back `skip_modified` ("create-once, and the file is already there"),
and five more footprint artifacts come back `skip_modified` with "exists and stayfixed did not
write it" — `ledger-runbook`, `bug-index`, `roadmap`, `roadmap-history` and `trail`, whose bytes
genuinely differ from the templates. The manifest records none of those five, and the second
assertion below constrains only what the manifest records, so the test could not see them: the
sentence claimed for fifteen artifacts what is true of seven.

**The divergence is the fixture's design, not its drift, which is why the sentence was narrowed
rather than the fixture rebuilt.** `tests/test_fixtures.py` runs every gate over this tree and
those five files are what the gates read — a bug index listing `BR-001`, a roadmap carrying the
trail listing, a `trail.toml` declaring a state per document, a bug-reports runbook. A fixture
regenerated from a clean `init` would carry the templates' empty forms instead (`render_index([],
bug_register(config))` lists no bug at all), so the gates would be checking a project with
nothing in it; and `init` could not write a `[ci] ref` for it either, because no released tag
names this version's commit. The honest claim is the narrow one, and it is the one asserted here.
"""

from __future__ import annotations

import shutil
from dataclasses import replace
from pathlib import Path

from stayfixed.config.loader import CONFIG_FILE, load
from stayfixed.project.api import project_templates
from stayfixed.release.api import Resolution
from stayfixed.scaffold import Manifest, Template, Verb, plan

ROOT = Path(__file__).resolve().parents[2]
SMOKE = ROOT / "tests" / "fixtures" / "smoke-project"


def test_the_smoke_fixture_is_a_project_init_has_nothing_left_to_create_in(tmp_path: Path) -> None:
    # Mutation (by hand — the fixture is data): change one byte of the `documentation.md` template
    # -> `documentation-policy` leaves `unchanged` and the last assertion reddens, and the fixture
    # is regenerated by running `stayfixed init --yes --no-ci` on a copy and committing the result
    # back. The seven artifacts that are the templates' own bytes are the ones this can see; the
    # five that are the fixture's own are `skip_modified` and are recorded nowhere, which the module
    # docstring states.
    root = tmp_path / "smoke"
    shutil.copytree(SMOKE, root)
    config = load(root, machine=tmp_path / "absent.toml")
    document = (root / CONFIG_FILE).read_text(encoding="utf-8")
    prepared = project_templates(
        config,
        resolution=Resolution(None, True),
        document=document,
        adopted=True,
    )
    once = plan(root, config, prepared.once)
    footprint = plan(root, config, prepared.footprint)
    # The walk is stated non-empty first: an empty artifact list would satisfy both assertions
    # below while proving nothing about the fixture at all.
    assert len(prepared.once) + len(prepared.footprint) >= 14
    assert not [a for a in [*once.actions, *footprint.actions] if a.verb is Verb.CREATE]
    records = Manifest.read(root).records
    assert set(records) and set(records) <= set(footprint.unchanged) | set(once.unchanged) | {
        a.artifact_id for a in once.actions if a.verb is Verb.SKIP_MODIFIED
    }
    # And the provenance each record carries is the one this build would write. `Record.template`
    # is committed and is where a reader finds out where an artifact's bytes came from,
    # and three of these artifacts compute their bytes rather than reading a shipped file — so a
    # record naming `project/<id>` for one of those points at a file the wheel does not carry.
    # This fixture's manifest carried exactly that for `gitignore` from the day it was grown.
    built = {t.id: t.source for t in (*prepared.once, *prepared.footprint)}
    assert {key: record.template for key, record in records.items()} == {
        key: built[key] for key in records
    }


def test_every_recorded_footprint_artifact_follows_a_template_change(tmp_path: Path) -> None:
    # Mutation (by hand, the manifest is data): put back one record's `sha256` from before a
    # change to its template's bytes, as the rename left four of them -> that artifact's reason
    # becomes "hand-edited" and the assertion reddens. A record whose digest is not the bytes on
    # disk makes `upgrade` call the fixture's own files hand-edited and skip them, which is the
    # regression the fixture exists to catch. The test above cannot see it, because with the
    # templates unchanged the plan compares the render and never reads the record.
    root = tmp_path / "smoke"
    shutil.copytree(SMOKE, root)
    config = load(root, machine=tmp_path / "absent.toml")
    prepared = project_templates(
        config,
        resolution=Resolution(None, True),
        document=(root / CONFIG_FILE).read_text(encoding="utf-8"),
        adopted=True,
    )
    records = Manifest.read(root).records

    def changed(template: Template) -> Template:
        return replace(template, render=lambda: template.render() + "\nchanged\n")

    recorded = [changed(t) for t in prepared.footprint if t.id in records]
    assert len(recorded) >= 7
    footprint = plan(root, config, recorded)
    assert {a.artifact_id: a.reason for a in footprint.actions} == {
        t.id: "refreshed" for t in recorded
    }
